### PR TITLE
[Translation zh-tw] Fundamentals, Tools, Billions, Updates

### PR DESCRIPTION
**Pull request by limhenry**
Translated all articles in fundamentals from [Simplified Chinese (zh-cn)](https://github.com/google/WebFundamentals/tree/master/src/content/zh-cn/fundamentals/) to Traditional Chinese

### CODE REVIEW

**Comment by limhenry** [comment]
Synced with [Simplified Chinese (zh-cn)](https://github.com/google/WebFundamentals/tree/master/src/content/zh-cn/)

 - /billions
 - /fundamentals
 - /tools
 - /updates

**Comment by limhenry** [comment]
Fixed:
 - First paragraph of [Critical Rendering Path, zh-CN](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/?hl=zh-cn)

Synced:
 - Critical Rendering Path (zh-CN and zh-TW)

**Comment by agektmr** [comment]
@petele This PR is good to be merged unless there's technical issues. Let me copy/paste the discussion at ChromiumDev#l10n Slack channel:

-------------------

agektmr [16 hours ago] 
Oh wow, did you translate them manually or with some kind of script?

henrylim [15 hours ago] 
Technically zh-CN and zh-TW are the same language, just characters are different. (zh-TW looks more complex). But you can convert it using Google Translate or any method (I am using a extension in VS Code to do that).

henrylim [15 hours ago] 
ie: 语 (zh-CN) and 語 (zh-TW) (_i believe you can understand this word also :stuck_out_tongue: _), it looks slightly different, but the grammar and meaning still the same :slightly_smiling_face:

agektmr [15 hours ago] 
ok, interesting. Then why in general both simplified and traditional Chinese are written separately?

henrylim [15 hours ago] 
not really sure about the reason. but china, malaysia, singapore are using Simplified Chinese. and Taiwan, Hong Kong, Macau are using Traditional Chinese

agektmr [15 hours ago] 
Ok, that makes sense. Thanks. Can you get review approval from @kennith in GitHub?

henrylim [15 hours ago] 
sure!

henrylim 
[15 hours ago] 
u might find this interesting :stuck_out_tongue: https://en.wikipedia.org/wiki/Debate_on_traditional_and_simplified_Chinese_characters
Wikipedia
Debate on traditional and simplified Chinese characters
The debate on traditional Chinese characters and simplified Chinese characters is an ongoing dispute concerning Chinese orthography among users of Chinese characters. It has stirred up heated responses from supporters of both sides in mainland China, Hong Kong, Macau, Taiwan, and among overseas Chinese communities with its implications of political ideology and cultural identity. Simplified characters here exclusively refer to those characters simplified by the People's Republic of China (PRC), instead Show more… (56 kB)

henrylim [15 hours ago] 
@agektmrcan i know which PR require approval?

agektmr [15 hours ago] 
https://github.com/google/WebFundamentals/pull/5377
GitHub
[Translation zh-tw] Fundamentals, Tools, Billions, Updates by limhenry · Pull Request #5377 · google/WebFundamentals
Translated all articles in fundamentals from Simplified Chinese (zh-cn) to Traditional Chinese
 
kennith [9 hours ago] 
@henrylim this will definitely speed up the translation! I reviewed them and they look very good.

**Comment by agektmr** [comment]
@limhenry Pete said this PR is too large. Is it possible to split this PR into like 5 articles each?

**Pull request closed without merging**
