### PR TITLE
[Translation ja] src/content/ja/fundamentals/performance/get-started/index.md

### PR DESCRIPTION
**Pull request by agektmr**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/ja/review/9349)

### CODE REVIEW

**Comment by petele** [comment]
@agektmr - is this good to go?

**Comment by silverskyvicto** [comment]
@googlebot I consent.

**Comment by agektmr** [comment]
@petele I think this is good to go.

**Comment by petele** [comment]
@agektmr  - Can you add your LGTM/review then please?

**Pull request merged**
