### PR TITLE
[ZH-CN] Tools > Workbox > Precache

### PR DESCRIPTION
**Pull request by kennith**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/zh-CN/review/6824)

### CODE REVIEW

**Comment by kennith** [comment]
@jzhangdev Did you signed the CLA?

**Comment by kennith** [comment]
@mt-gitlocalize Did you sign the CLA?

**Comment by jzhangdev** [comment]
@kennith I have already signed.

**Comment by limhenry** [comment]
@agektmr could you check this? (something wrong with the CLA?)

**Comment by agektmr** [comment]
@jzhangdev can you check at [https://cla.developers.google.com/clas](https://cla.developers.google.com/clas)?

**Comment by agektmr** [comment]
Did you use the same email address for signing CLA as the one used to commit?

**Comment by jzhangdev** [comment]
@agektmr I just checked, I am using the same email

**Comment by agektmr** [comment]
GitLocalize CLA matter is resolved. This pull request may be merged if reviewers can give LGTM.
cc: @kennith @limhenry 
Sorry @jzhangdev for letting you wait for long time.

**Pull request closed without merging**
