### PR TITLE
Upgrade Gulp to V4, support latest version of Node

### PR DESCRIPTION
**Pull request by chybie**
Upgrade Gulp to version 4. Support latest version of Node (12+) as well as some old ones.

### Tests

Environments:  ✅ **Node 10, 11, 12**.

Please run `npx gulp --tasks` to view the full list of Gulp tasks and its dependencies.

Gulp commands tested:
✅ `npx gulp build`
✅ `npx gulp post-install`
✅ `npx gulp clean`
✅  `npx gulp test`
✅ `npx gulp update-updated_on`
✅ `npx gulp workbox`

Gulp commands NOT able to test 
*(are there deprecated? Seems like these commands aren't use in anywhere)*
🟡 `npx gulp claat:all`

### What's changed?
This PR update the Gulp to v4:
- remove `run-sequence` lib
- replace `run-sequence` with Gulp v4 built-in `series` and `parallel`
- signal the end the tasks [callback, promise or async](https://gulpjs.com/docs/en/getting-started/async-completion)
- move a few gulp tasks into `private` functions`

### Context

Currently, the project is not able to start `npm start`, build `npm build` or install `npm install`. User will run into this error.

```
primordials is not defined
```

This error is caused by the outdated Gulp version 3.9. The current workaround is downgrade node to v11 or v10, but that's not ideal. 
 

### Checks
- [ ] This has been reviewed and approved by (NAME)
- [x] I have run `npm test` locally and all tests pass.
- [x] I have added the appropriate `type-something` label.
- [ ] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele

### CODE REVIEW

**Comment by chybie** [comment]
Hi, @jeffposnick Is the `gulp workbox` command still in use? 
Not able to run the task as it requires a file `/src/data/githubKey.txt`.

**Comment by jeffposnick** [comment]
👋 @chybie 

Yes, we still use `gulp workbox` to publish the Workbox docs each time there's a major release. (At least for the time being; longer-term we plan on migrating to something different.)

You should be able to use the steps at https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token to generate a read-only `repo` GitHub token and save it in the `GITHUB_TOKEN` environment variable if you want to test out the full `gulp workbox` flow.

**Comment by chybie** [comment]
Thanks @jeffposnick . Set up the token and tested pass! Updated my comments.

**Comment by chybie** [comment]
Hi @petele, do you know if the `gulp claat:all` is still in use?

**Comment by petele** [comment]
@chybie - `gulp claat:all` is manually run occasionally, but trying to deprecate it as quickly as possible.

There is one other gulp file, not checked into the repo that is used for deploying that will need to be updated, I'll email you with details.

**Comment by petele** [comment]
Based on back-channel conversations with @chybie, I'm going to close this for now, but will keep the branch around.

**Comment by pimterry** [comment]
I just ran into this - it means that `npm install` fails for Node 12+. Node 10 is pretty old now (it's maintenance only LTS and goes full EOL in April) and this PR is the only documentation of this issue, so I suspect this blocks most outside contributors.

The Getting Started docs say that node 10 - 12 works, which AFAICT is wrong, Node 12 consistently fails with this same `primordials is not defined` error on my machine. Might be good to get this or at least the documentation updated.

**Pull request closed without merging**
