### PR TITLE
Add display-mode article

### PR DESCRIPTION
**Pull request by kenchris**
Add an article about display-mode which is already shipping

### CODE REVIEW

**Comment by kenchris** [comment]
I signed it!

**Comment by PaulKinlan** [comment]
Why close it?

**Comment by PaulKinlan** [comment]
Ah

**Comment by kenchris** [comment]
@PaulKinlan It was a mistake

**Comment by kenchris** [comment]
Error: Invalid Author 'kenchris' found in  en/updates/posts/2015/10/display-mode.markdown 

@PaulKinlan I guess you need to fix this, somehow

**Comment by PaulKinlan** [comment]
@kenchris you need to pull in the PR I have on your repo so that it gets picked up by this repo

**Comment by kenchris** [comment]
OK let me try that

**Pull request merged**
