### PR TITLE
[Bahasa Indonesia] Localized ID content for web section (first page)

### PR DESCRIPTION
**Pull request by abdshomad**
Hi @petele, @tyohan, I have re-worked the Indonesian Translation of Web Fundamentals per section. 
This PR is for "web" section (the first page). 

I have tested it running on my local development version. Here's the screenshot: 

next-version-id-001

Please review it. 

I have translated several other sections under Web Fundamentals such as : 
* getting-started
* design-and-ui
* discovery-and-monetization
* engage-and-retain
* native-hardware
* performance
* primers
* security

and will submit separate PR for each of the above sections separately.

### CODE REVIEW

**Comment by petele** [comment]
Replaced by #3671 

Hey @abdshomad - this is great. We switch to `master`, so I recreated this PR as #3671 and will merge it momentarily. Please update your fork and work from the master branch now. I'll be removing the next-version branch shortly.

Thanks!

**Comment by petele** [comment]
And we're live! https://developers.google.com/web/?hl=id

**Comment by abdshomad** [comment]
Kewl! Will commit next translation batches... (after my travel finished)

**Comment by mychaelgo** [comment]
@abdshomad need help? 😄

**Comment by abdshomad** [comment]
Sure @mychaelgo :) Can we collaborate to translate the whole Web**Fundamentals** be available for Indonesian developers? We can work on the translation by sections, then review the translation each others. Now, Im working on these sections: 

* security (30%) 
* getting-started (100%)

You might want to help with other sections. Let's collaborate using Google Spreadsheet to track the translation assignment and status here:  https://docs.google.com/spreadsheets/d/1B3FrBrlV_xjMrTzVPFrJ24eJFWJC1YtvEgLhQxyhJA0/edit#gid=0

**Comment by mychaelgo** [comment]
@abdshomad ok, i have request access to your gdocs

**Pull request closed without merging**
