### PR TITLE
LitElement & lit-html release update

### PR DESCRIPTION
**Pull request by arthurevans**
What's changed, or what was fixed?
It's a new update! For lit-html and LitElement!

**Target Live Date:** 2019-02-05

Trying to coordinate several items for release, please don't push this live without me. 

- [ ] This has been reviewed and approved by @kaycebasques
- [x] I have run `npm test` locally and all tests pass.
- [ ] I have added the appropriate `type-something` label.
- [x] I've staged the site and manually verified that my content displays correctly.

Q: What the heck is a `type-something` label?

**CC:** @petele

### CODE REVIEW

**Comment by arthurevans** [comment]
Warning #1 is the word "nodes" and is not a typo for Node. 

Warning #2 should be fixed now...

**Comment by arthurevans** [comment]
#1, as explained before, not a typo.
#2, Material Design matches the usage in the devsite style guide & the Material Design site so not sure why it's wrong. I think this guidance might have changed at some point ...

**Comment by rictic** [comment]
`type-something` is probably a set of PR labels?

**Comment by arthurevans** [comment]
Thanks @kaycebasques !

**Pull request merged**
