### PR TITLE
Tweaks to Save-Data WF Update

### PR DESCRIPTION
**Pull request by samdutton**
Great article @igrigorik! 

A few nitpicky suggestions.

### CODE REVIEW

**Comment by jpmedley** [comment]
@samdutton 

Your formatting change on line 76 makes that note inconsistent with the rest of the page. Can you please change it back?

Joe

**Comment by samdutton** [comment]
Problem is, a stray underscore is displayed on the page as it is.

> inconsistent with the rest of the page

The other notes onthis page are italic — or do you mean something else?

**Comment by igrigorik** [comment]
This looks good.. indeed, missed the stray underscore in there. :+1: thanks Sam!

**Comment by jpmedley** [comment]
I misinterpreted the file change. Request withdrawn. (Sorry about that.)

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Pull request merged**
