### PR TITLE
[TRANSLATION] EN to JA: your-first-progressive-web-app/step-03

### PR DESCRIPTION
**Pull request by yoichiro**
I just translated the step-03 file from EN to JA in the progressive web app section. It would be great if someone can review my committed files and merge them. Thank you in advance.

### CODE REVIEW

**Comment by yoichiro** [comment]
@agektmr Could you review this PR?

**Comment by yoichiro** [comment]
@agektmr @PaulKinlan Also, I fixed an issue regarding a homepage link of the translator in each translated article. It would be great if you guys can review the modification to fix the issue.

**Comment by agektmr** [comment]
Translation LGTM

**Comment by PaulKinlan** [comment]
This looks good.  Interestingly our staging environment doesn't render your image because it is pulling from the master branch (we need to sort that) but everything looks fine.

**Comment by PaulKinlan** [comment]
Thank you again for the work on this.  It is amazing.

**Comment by yoichiro** [comment]
@agektmr @PaulKinlan Thank you for the confirmations. :)

**Pull request merged**
