### PR TITLE
Add Snippets guide

### PR DESCRIPTION
**Pull request by kaycebasques**
hallo @pbakaus 

* Continuation of #2043
* New commits address last round of feedback from #2043, see that PR for inline discussions
* Animations don't work, see #1890
* Question: I really don't know where to house this. Snippets resides in the Sources panel. It doesn't make sense to store it with the Command Line docs. I've stored it top-level in Debug, but I don't know how or where we would display it. It's currently buried / hidden on the Debug index page.

### CODE REVIEW

**Comment by pbakaus** [comment]
Nice!

Instead of putting it directly in the debug/ folder, create a sub directory called "snippets", put the markdown file there and rename it to "index.markdown". Then change the title from "Set Up Snippets" to "Using Snippets" (or something even better). This will make it appear in the left nav.

Unfortunately WF currently isn't setup to skip the forth indentation, so on the snippets page you'll see an empty "topics" block at the bottom. My guess is that this will be fixed eventually and is fine for now.

Regarding the video descriptions: I still don't like em. @Meggin feel free to chime in here. I don't think they have a lot of value. I propose the following: Let's always make sure that the text on the page works standalone without videos, and use the videos as "bonus visualization". This gets us to the same place without awkwardly describing the contents of a video.

**Comment by paulirish** [comment]
"Using JavaScript Snippets"  and i'd position it alongside any Using the Console stuf.

**Comment by petele** [comment]
@pbakaus - when this is ready to go, please add the 'lgtm: approved' label

**Comment by kaycebasques** [comment]
OK @pbakaus and @paulirish all items addressed, and then some. See last batch of commits.

**Comment by pbakaus** [comment]
LGTM, nice work!

**Comment by petele** [comment]
Merged, will most likely push a new build tomorrow.

**Pull request merged**
