### PR TITLE
Fixes #3577 - adds default 100px height to framebox

### LINKED ISSUE #3577: Framebox without height behaves differently in dev & live
Discovered in #3564.

```
{% framebox %}
```

…on the dev server this produces `<iframe style="width: 100%;" …>`. On live it produces `<iframe style="width: 100%; height: 100px;" …>`.

### PR DESCRIPTION
**Pull request by PaulKinlan**

### CODE REVIEW

**Comment by petele** [comment]
Is this the same default height used by DevSite?

**Comment by ebidel** [comment]
The Devsite style guide doesnt say, but I suspect the default is "auto".

**Comment by PaulKinlan** [comment]
Jake suggested the default is 100px

**Comment by jakearchibald** [comment]
It is

**Pull request merged**
