### PR TITLE
Delete store-credentials.md

### PR DESCRIPTION
**Pull request by Meggin**
We moved store content into the save doc, and also removed it from TOC, but never removed the file from the repo.

What's changed, or what was fixed?
- item 1
- item 2

**Fixes:** #issue

**Target Live Date:** YYYY-MM-DD

- [ ] This has been reviewed and approved by (NAME)
- [ ] I have run `gulp test` locally and all tests pass.
- [ ] I have added the appropriate `type-something` label.
- [ ] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele

### CODE REVIEW

**Comment by agektmr** [comment]
As I said in an email earlier, I'm worried that this will remove content about storing FederatedCredential completely. Can you move the Federated Credential part of this page to one of other pages?

**Comment by petele** [comment]
@Meggin - can you address @agektmr's comment, and also set up a redirect in the `_redirects.yaml` to redirect this to the new file where the content lives?

**Comment by agektmr** [comment]
Meggin clarified the doc is already moved to other page. I will add _redirect in separate pull request.
LGTM.

**Comment by petele** [comment]
I've added the redirect to this PR and will merge.

**Comment by Meggin** [comment]
Thanks, Pete.

**Pull request merged**
