### PR TITLE
[Translation ja] src/content/ja/fundamentals/architecture/app-shell.md

### PR DESCRIPTION
**Pull request by agektmr**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/ja/review/9271)

### CODE REVIEW

**Comment by silverskyvicto** [comment]
@googlebot I consent

**Comment by petele** [comment]
@agektmr - is this good to go?

**Comment by agektmr** [comment]
@petele yes, I think it's good to go.

**Comment by petele** [comment]
@agektmr - can you add your LGTM/review please

**Pull request merged**
