### PR TITLE
Corrections & updates

### PR DESCRIPTION
**Pull request by jakearchibald**
Happy to publish this now. People have seen it in RSS & such.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Is this ready to go live?

**Comment by jpmedley** [comment]
@PaulKinlan @jakearchibald I'm doing a copy edit real quick.

**Comment by jpmedley** [comment]
I'll do it after the merge.

**Comment by petele** [comment]
@jpmedley - lmk when/if i should merge

**Comment by PaulKinlan** [comment]
If we merge it then Joe can do a edit pass directly in this repo, we just need to not push it live.

**Comment by jakearchibald** [comment]
I'm happy for it to go live

**Pull request merged**
