### PR TITLE
Building for Billions draft, and updates to nbu branch

### PR DESCRIPTION
**Pull request by samdutton**
This consists of: 
* The new file _billions.markdown_ (which replaces _building-for-billions.markdown_).
* Updates to synchronise with the master branch.

### CODE REVIEW

**Comment by samdutton** [comment]
I signed it!

**Comment by jpmedley** [comment]
@samdutton I've never seen a PR like this. Did you combine a bunch of work from other people?

**Comment by samdutton** [comment]
@jpmedley  Agree it looks odd!

A few weeks ago I created the nbu branch (at Pete's suggestion), then today I forked it, added a new file (web/billions.markdown) and deleted a file (web/building-for-billions.markdown).

I can delete the fork and start again, if that's easier.

**Comment by PaulKinlan** [comment]
@samdutton can you rebase it at least, there are so many changes in here that are not related to the actual commit it is hard to work out if they are good or bad changes.

**Comment by samdutton** [comment]
Sure — I'll redo it.

**Comment by samdutton** [comment]
Actually — I'm going to kill this PR and start again.

**Pull request closed without merging**
