### PR TITLE
New Getting Started section for Performance: Measuring Performance doc and all images

### PR DESCRIPTION
**Pull request by dgash**
New Getting Started section for Performance: Measuring Performance doc and all images

### CODE REVIEW

**Comment by Meggin** [comment]
I approved this pull request; however, see my feedback above to make the images look better using the shadow technique.

**Comment by Meggin** [comment]
The new images are great, but still gonna keep this open, to improve the appearance of remaining images by adding the shadow effects. Basically you use these commands on the same photos: Cmd + Shift + 4 + spacebar + click, and the image will get a nice shadow background around it, which makes it look quite a bit cleaner. For an example of what I mean, check out images in this doc that uses that technique: https://developers.google.com/web/tools/chrome-devtools/.

One trick of getting this to work quickly is to open each existing photo in it's own tab, shrink it down, and then use the commands. That way you are taking a picture of the picture, and getting the shadow effects.

**Comment by addyosmani** [comment]
Hey folks. Do we know what the current status of this PR is? I see Dave landed some follow up commits to the shadow comments in https://github.com/google/WebFundamentals/pull/5182/commits/9c539db35d6c4236313014137bd08edee1bfa121. Are we closer to landing this?

**Comment by Meggin** [comment]
Hey,

I will do a full sweep Thursday morning to give a proper status.

Wasn't able to do this over the past few weeks due to GDD India deadlines.

Meggin

**Comment by addyosmani** [comment]
@Meggin If possible, could @kaycebasques take a look through this PR too as he's been coordinating the docs for our tooling narrative? I'd like to make sure the tools we're recommending here fit in with our recommendations elsewhere.

**Comment by Meggin** [comment]
Yes, that is doable. I'll add Kayce here as a reviewer and chat with him too.

**Comment by kaycebasques** [comment]
Righty-O

**Comment by petele** [comment]
I've added the `DO NOT MERGE` tag, once this is ready, please remove it and i'll take a final look and merge.

**Comment by petele** [comment]
Looks like the build is failing, once that's fixed, @addyosmani, please **_squash and merge_** when you're ready.

**Pull request merged**
