### PR TITLE
update screenshots on devtools homepage

### PR DESCRIPTION
**Pull request by kaycebasques**
Just replacing the slightly old screenshots with fresh ones. This should be good to go.

### CODE REVIEW

**Comment by kaycebasques** [comment]
Build fail probably related to the DNS attack:

```
$ git fetch --no-tags --depth=1 origin +refs/pull/3758/merge:
fatal: unable to access 'https://github.com/google/WebFundamentals.git/': Couldn't resolve host 'github.com'
[info] build failed (exit code 1)
```

**Comment by petele** [comment]
Yah, not too worried about the build failing right now. It looks like you changed a bunch of images out and added new ones, did you delete the old ones if they're not being used?

**Comment by kaycebasques** [comment]
Old screenshots have now been deleted.

**Comment by marccantin** [comment]
STOP YOUR SPAM!!!!!!!!!!!!!!!!

2016-10-21 16:06 GMT-04:00 Pete LePage <notifications@github.com>:

**Comment by marccantin** [comment]
STOP YOUR SPAM!!!!!!!!!!!!!!!!

2016-10-21 16:54 GMT-04:00 Kayce Basques <notifications@github.com>:

**Pull request merged**
