### PR TITLE
typography/variable-fonts Minor corrections

### PR DESCRIPTION
**Pull request by davelab6**
This PR supplies copy corrections to the recent variable fonts article

**CC:** @petele

### CODE REVIEW

**Comment by petele** [comment]
@mustafa-x - would you please review and approve/request updates?

**Comment by mustafa-x** [comment]
need to fix one css bug in the examples, it says `font-variations-setting`

It should be `font-variations-settings` otherwise thumbs up from me.

**Comment by davelab6** [comment]
Fixed! Please squash :)

**Comment by mustafa-x** [comment]
Sweet looks good to me. Make sure you pull from master :) I think some things were merged today. Or is it automatic @petele ?

**Comment by davelab6** [comment]
@mustafa-x Thanks for hopping on this :) I see 

> At least one approved review is required by reviewers with write access.

I believe this means you need to hit the "approve" green button in the review mode

**Comment by davelab6** [comment]
Thank you both!

**Pull request merged**
