### PR TITLE
Fix the image source 

### PR DESCRIPTION
**Pull request by Kanguanda**
https://github.com/google/WebFundamentals/issues/2540

The name I used to sign the CLA is osvaldo abel

### CODE REVIEW

**Comment by Zayvier** [comment]
I don't recall doing any requests, plus I wish I understood half the emails
this site sends me... I wish I could learn faster! :x

**Comment by Kanguanda** [comment]
The name I used to sign the CLA is Osvaldo Abel

**Comment by Kanguanda** [comment]
I signed it!

**Comment by Kanguanda** [comment]
I signed it!

**Comment by Kanguanda** [comment]
I signed it!

**Comment by Kanguanda** [comment]
it is me 

Date: Mon, 8 Feb 2016 20:29:40 -0800

**Comment by petele** [comment]
Hi, thanks for the PR. It looks like this PR contains several different changes and that are un-related to what you're trying to fix. We generally try to maintain PRs as a single set of changes, so I'm going to change this and request you submit a new one that is just a single set of changes.

thanks,
PEte

**Comment by Kanguanda** [comment]
ok @petele, and please make me know when change this :) 
i'm going to continue  looking for some more things here to contribute.

Thanks

**Pull request closed without merging**
