### PR TITLE
Translation: translate getting-started/your-first-progressive-web-app into simplified Chinese

### PR DESCRIPTION
**Pull request by wy-ei**
translate the `getting-started/your-first-progressive-web-app` section into simplified Chinese.

### CODE REVIEW

**Comment by wy-ei** [comment]
I signed it!

**Comment by petele** [comment]
Hey @wy-ei, it looks like the build failed because there are some invalid tags in the post. Can you please take a look, make sure it builds on your system and  then update the PR?

Thanks for the contribution!

**Comment by wy-ei** [comment]
@petele when i build on may Mac, I meet this error:

```
/WebFundamentals/src/jekyll/_plugins/pages/WFPage.rb:209:in `handleInvalidKeys': Invalid keys in YAML in zh-cn/fundamentals/getting-started/index.markdown (RuntimeError)
```

I guess this is not my problem, the content in index.markdown is below:

```
---
layout: shared/narrow-subdirectories-list
title: "开始"
description: "分步教程帮你一步步学会你需要的东西。"
published_on: 2015-07-21
updated_on: 2015-07-21
translation_priority: 0
order: 1
translators:
  - samchen
  - henrylim
  - wangyu
---
```

**Comment by petele** [comment]
You need to remove `layout`, `published_on`, `order`, `authors` from the document YAML, those aren't allowed in translated files since they're picked up from the English version.

**Comment by wy-ei** [comment]
oh,I don't see this notice before. I will make some change and PR again.

**Comment by wy-ei** [comment]
@petele I have fix it!

**Comment by petele** [comment]
@wy-ei - looks good, thanks!

**Pull request merged**
