### PR TITLE
[Translation zh-tw] Fundamentals > Related Guides

### PR DESCRIPTION
**Pull request by kennith**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/zh-TW/review/431)

### CODE REVIEW

**Comment by agektmr** [comment]
@sotayamashita @chikathreesix can you take a look?

**Comment by sotayamashita** [comment]
@agektmr I'll check it out.

**Comment by sotayamashita** [comment]
@kennith I would appreciate if you could remove extra code by yourself because I cannot find the branch. :bow:

**Comment by petele** [comment]
@kennith - can you take a look please?

**Comment by petele** [comment]
I'm going to close this for now, please resubmit when it's been updated.

**Pull request closed without merging**
