### PR TITLE
Update _mdl-overrides.scss

### PR DESCRIPTION
**Pull request by sgomes**
Workaround for Safari scrolling bug.

@petele @PaulKinlan Please test.

### CODE REVIEW

**Comment by gauntface** [comment]
I can't see any reason not to go with this. LGTM

**Comment by petele** [comment]
Merged and pushed live.

**Comment by ricardobeat** [comment]
@petele the issue is still there. Is there a delay before it reaches live servers?

**Comment by petele** [comment]
This only fixed the scroll prevention, not the fact it jumps. We're working on moving to a new infrastructure that'll eliminate that issue completely.

**Comment by ricardobeat** [comment]
@petele not sure what you mean - scrolling in Safari is still not possible at all: https://cdn.pbrd.co/images/e55f14PTf.gif

**Comment by petele** [comment]
@sgomes - can you take another look please?

**Comment by sgomes** [comment]
@petele The fix doesn't seem to be live, as far as I can tell.

**Comment by petele** [comment]
Just did another push, and I see the transform in the CSS and with Safari 9.1.1 on my Mac, I'm able to scroll just fine. I *think* that did it.

**Comment by jyasskin** [comment]
https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web?hl=en#user-gesture-required still doesn't work in Chrome, even though #2954 was duped to this PR.

**Comment by sgomes** [comment]
That's a bad dupe, sorry about that @jyasskin. The follow up to that one is #2291

**Pull request merged**
