### PR TITLE
Update Lighthouse doc concerning "Optimize Images"

### PR DESCRIPTION
**Pull request by xiatianyu**
Updated to reflect the following changes made to the "Optimize Images" Lighthouse audit:
* This audit now tests both JPEG and WebP images.
* The highest permissible JPEG quality has been bumped from 85 to 92 since [#2354](/GoogleChrome/lighthouse/commit/e84530e7329f0f025670bcb82ca6e5022f0b8551#diff-fd190dc3127d17941b6683b1a8c4ece6).

**CC:** @petele @patrickhulce

### CODE REVIEW

**Comment by xiatianyu** [comment]
I signed it!

**Comment by patrickhulce** [comment]
Thanks for the patch @xiatianyu! I think there might be a bit of confusion between the gatherer and the audit in Lighthouse though :)

The optimized-images gatherer collects both JPEG and WebP data as you identify, but there are two different audits consuming its output. One that just looks at JPEG data (the one that the audit document is for), and one that just looks at WebP data.

**Comment by petele** [comment]
Any updates on this?

**Comment by patrickhulce** [comment]
I think we can close this. The current documentation is correct given how we structure the audits in Lighthouse and while it could use an update to shy away from specifying "compression level 85", moving it to 92 doesn't really help clarify what we're talking about.

**Comment by kaycebasques** [comment]
Whoops, just saw Patrick's comment. Closing.

**Pull request closed without merging**
