### PR TITLE
chore(link): update link issue for Custom Elements extends

### PR DESCRIPTION
**Pull request by LasaleFamine**
Updating link for the issue related to native elements extension. (https://github.com/w3c/webcomponents/issues/662)

### CODE REVIEW

**Comment by ebidel** [comment]
I prefer if we keep the link as-is. It has all the historical discussion.

**Comment by LasaleFamine** [comment]
Oh, I understand. Actually I was thinking could be misunderstanding come up on a closed issue as reference. A new folk can assume is a "closed argument" instead of scrolling down the whole page and find the correct issue. Maybe is worth adding also the new issue within the old one? I don't know. If not, we can close this one then.

**Comment by ebidel** [comment]
Ok, let's add a link to the new one in addition to the old one. Sound good?

**Comment by LasaleFamine** [comment]
Yep, sounds good for me. Do you have some specific copy to add to explain that there are two main issues?

**Comment by petele** [comment]
@ebidel - when you're happy with this, feel free to merge.

**Comment by ebidel** [comment]
@LasaleFamine 

"Voice your thoughts on 509 and 662". Include the links of course.

**Comment by LasaleFamine** [comment]
@ebidel I think I have problems with some languages (like Chinese). Someone can help with this?

**Comment by kaycebasques** [comment]
Thanks for the contribution @LasaleFamine

**Pull request merged**
