### PR TITLE
Update step-07.markdown

### PR DESCRIPTION
**Pull request by emmynet**
Wrong curl request params

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Hey, thanks for the PR. I know it is only a small commit, but we really need you to sign the CLA

**Comment by emmynet** [comment]
. I signed it!
Il 15/Apr/2016 19:55, "Paul Kinlan" <notifications@github.com> ha scritto:

**Comment by PaulKinlan** [comment]
Now, iirc we've changed this a number of times in the past.

Every example that I have seen of this has the " around all of the Content-Type header, and not after the ":"..... which is correct and why?

**Comment by emmynet** [comment]
I've tested curl on MacOsx and it doesn't work.

After many tests I have succeeded by doing the same thing that you have
done in your Demo:

https://simple-push-demo.appspot.com/

I thing that the problem is curl's version on MacOsx because now i tried on
linux (curl version 7.47.0) and it works in both ways!


Il 15/Apr/2016 21:51, "Paul Kinlan" <notifications@github.com> ha scritto:

Now, iirc we've changed this a number of times in the past.

Every example that I have seen of this has the " around all of the
Content-Type header, and not after the ":"..... which is correct and why?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/google/WebFundamentals/pull/2807#issuecomment-210616204>

**Comment by petele** [comment]
It looks like the [proper syntax](http://stackoverflow.com/questions/356705/how-to-send-a-header-using-a-http-request-through-a-curl-call) for curl is to quote the whole header, not just the value.

I'm going to close for now, if you can find something that indicates otherwise, please re-open.

**Pull request closed without merging**
