### PR TITLE
Updates to lazy loading images and video guide.

### PR DESCRIPTION
**Pull request by malchata**
What's changed, or what was fixed?
- Added short section on native lazy loading.
- Added short section on SEO considerations.
- Tweaked and edited prose.
- Tweaked some code blocks.

**Target Live Date:** Whenever's convenient.

- [ ] This has been reviewed and approved by @addyosmani
- [x] I have run `npm test` locally and all tests pass.
- [ ] I have added the appropriate `type-something` label.
- [x] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele @addyosmani

### CODE REVIEW

**Comment by petele** [comment]
@addyosmani - can you take a look, then merge once you're happy please?

**Comment by malchata** [comment]
Hey, @petele, @addyosmani.

The content in the native lazy loading section is out of date. I didn't realize the implementation had changed, so please don't merge this until I update it. I'm on the road, but should be able to get to it over the weekend.

**Comment by addyosmani** [comment]
Happy to hold off until further updates ate made. Thanks for looking at this, @malchata!

**Comment by malchata** [comment]
Closing because I don't have time to rectify.

**Pull request closed without merging**
