### PR TITLE
Add Uploadcare to the list of GIFs to video convertors

### PR DESCRIPTION
**Pull request by rsedykh**
What's changed, or what was fixed?
- Added Uploadcare to the list of GIFs to video convertors

**Fixes:** #7543
**CLA name**: @rsedykh

content-new
section-tools
type-Content

**Target Live Date:** YYYY-MM-DD

- [ ] This has been reviewed and approved by (NAME)
- [ ] I have run `npm test` locally and all tests pass.
- [ ] I have added the appropriate `type-something` label.
- [ ] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele (previous reviewer on the same subject was @kaycebasques)

### CODE REVIEW

**Comment by rsedykh** [comment]
@kaycebasques ping. :-)

**Comment by PaulKinlan** [comment]
Why have we included this? It makes no sense in the context of the next sentence. Is this just opportunistic advertising? Have we done due diligence on this service?

**Comment by PaulKinlan** [comment]
@petele

**Comment by rsedykh** [comment]
Hello @PaulKinlan. We are here to give value to developers looking to solve the GIF problem.

There aren't many services that provide on-the-fly GIF to video conversion: Cloudinary does, and we also do — https://uploadcare.com/docs/image_transformations/gif2video/. We introduced the functionality a couple of years ago (https://www.producthunt.com/posts/uploadcare-3-0).

We've been serving adaptive media for seven years already for customers including Mozilla, Facebook, Webflow. We developed and open-sourced the fast and reliable image resizing algorithm (https://news.ycombinator.com/item?id=14712146) to help spread the word about Responsive Images and leverage the inequality in implemented techs between smaller and larger companies.

My intent was in line with promoting democracy on the web and diversifying the set of provided solutions for the problem of weighty GIFs and hence, slower web. If you'd allow me, I would love to research if anybody else provides the same functionality so we could further expand the list.

**Pull request merged**
