### PR TITLE
Dev Feedback on Home Page

### PR DESCRIPTION
**Pull request by petele**
Here's what I've got for the landing page.

screen shot 2017-01-25 at 1 17 41 pm

### CODE REVIEW

**Comment by robnyman** [comment]
Looks good to me!
Out of interest, do you plan to have something to the right of it? Since I guess it will be 2 two-col layouts, one on top of the other.

**Comment by petele** [comment]
No, was going to leave the right empty. When it goes full width, it doesn't look right. And we may add something there in the future.

**Comment by robnyman** [comment]
Ah, got it. Thanks!

**Comment by vikaskyadav** [comment]
Hey,

Not a big issue I guess but why so much emphasis on the word "downasaur"?

**Comment by petele** [comment]
@drufball - any comments before I merge?

**Pull request merged**
