### PR TITLE
Add Presentation API Update and update MediaRecorder demo link in WebRTC Update

### PR DESCRIPTION
**Pull request by samdutton**
R: @mounirlamouri @jpmedley

### CODE REVIEW

**Comment by petele** [comment]
@samdutton - LMK when this is good to merge, I don't see any comments from anyone so I assume it's not ready to go.

**Comment by PaulKinlan** [comment]
It had some feedback internally that same needs to sort

**Comment by samdutton** [comment]
Still needs tweaking — got email comments from Mounir/Anton this morning
(basically Chrome only supports the API connecting to a Cast device).

**Comment by samdutton** [comment]
@jpmedley PTAL — this has been through a few iterations now :).

@avayvod Thanks for your suggestions! I've made your changes and added a sentence about filing bugs and feature requests.

**Comment by samdutton** [comment]
@jpmedley PTAL — I've re-jigged this (and added new code samples) as per the email thread. The version on my fork [here](https://github.com/samdutton/WebFundamentals/blob/master/src/content/en/updates/posts/2015/11/presentation-api.markdown) is slightly more readable.

@avayvod Let us know if you'd like anything else changed.

**Pull request merged**
