### PR TITLE
Web payments docs

### PR DESCRIPTION
**Pull request by dgash**
What's changed, or what was fixed?
- Fixing files, trying to get them to stage...

**Fixes:** #issue

**Target Live Date:** YYYY-MM-DD

- [ ] This has been reviewed and approved by (NAME)
- [ ] I have run `npm test` locally and all tests pass.
- [ ] I have added the appropriate `type-something` label.
- [ ] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele

### CODE REVIEW

**Comment by petele** [comment]
What's the status on this?

**Comment by Meggin** [comment]
Dave, are these ready for review? Do you want Eiji to review as well?

**Comment by agektmr** [comment]
@Meggin these are intentionally staged and left there in order to show our internal reviewers get the idea of how entire doc set will look as they are massive amount. PMs are reviewing these separately.

**Comment by dgash** [comment]
Yes, what Eiji said. :-) They are under review by other PMs and are
currently just staged for looks.
d.

**Comment by Meggin** [comment]
Cool, thanks.

**Comment by agektmr** [comment]
This looks good to me now. @petele can you merge?

**Comment by PaulKinlan** [comment]
Checked it out on staging - everything looks ok.

**Pull request merged**
