### PR TITLE
Long nav items wrap

### PR DESCRIPTION
**Pull request by ebidel**
R: @petele 

screen shot 2016-07-07 at 2 55 34 pm

### CODE REVIEW

**Comment by petele** [comment]
Hey @ebidel, I'm hesitant to merge this one because I'm afraid it'll hide too much of the navigation. I'm worried that you won't necessarily be able to find what you're looking for if it's cut off. 

Thoughts?

**Comment by ebidel** [comment]
I was worried about that too. For longer items it really helps but for
shorter ones it could be harder to find things. Your call.

**Comment by jpmedley** [comment]
Option 3: Edit the titles to make them shorter where possible and where it
isn't, follow our push message advice and "Put important information up
front". After the later, Eric's suggestion would be more reasonable.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by ebidel** [comment]
Proposed a `shortname` metadata field: https://github.com/google/WebFundamentals/issues/3101

**Pull request closed without merging**
