### PR TITLE
Custom elements v1 article

### PR DESCRIPTION
**Pull request by ebidel**
R: @arthurevans @jpmedley cc @petele 

Article has had a technical review. PR also adds a nice "talking head" card to the site:

screen shot 2016-07-07 at 1 16 23 pm

### CODE REVIEW

**Comment by petele** [comment]
Looks good, will merge. did a publish today, will do one again tomorrow morning ET.

**Comment by ebidel** [comment]
Might want to wait for @jpmedley or @arthurevans . I don't know if they've had time to look at it yet.

**Comment by petele** [comment]
Er - OK, merged already... I'll publish tomorrow, if there are copy edits we can push those as they come in...

**Comment by arthurevans** [comment]
Sorry Eric, I meant to get to this last week, been buried. Will take a look tomorrow.

**Pull request merged**
