### PR TITLE
Improve the "Your first multi-screen site" guide

### PR DESCRIPTION
**Pull request by rmacklin**
Addresses most of the issues listed in https://github.com/google/WebFundamentals/issues/2391.

(Per [CONTRIBUTING.md](https://github.com/google/WebFundamentals/blame/6337ebea2d3b5a18b43107ad42623f0c4daa404d/CONTRIBUTING.md#L29)) The name I used to sign the CLA is Richard Macklin.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
I'll go through this in more depth this coming week.

**Comment by rmacklin** [comment]
@PaulKinlan let me know if you've had a chance to look over this.

**Comment by crhym3** [comment]
Hey @rmacklin would you be able to rebase this PR on master? When you do the CI will be able to stage your changes at a unique URL automatically.

**Comment by rmacklin** [comment]
@crhym3 Rebased!

**Comment by crhym3** [comment]
hm... strange. the build keeps failing with the same error:

```
Liquid Exception: No such file or directory @ rb_sysopen - 
src/content/en/fundamentals/getting-started/your-first-multi-screen-site/_code/fixingfirstbreakpoint.html
in 
src/content/ar/fundamentals/getting-started/your-first-multi-screen-site/responsive.markdown
```

**Comment by rmacklin** [comment]
My last commit had previously removed that file (https://github.com/google/WebFundamentals/commit/11c0116c1a57ec861cf2bd982d84d7c316246a34#diff-6d4f2a1527eac2604b7b5b0880c56140), but I've added it back to fix that error.

**Comment by crhym3** [comment]
Cool. Thanks!
This PR is now staged at https://pr-2392-dot-weasel-dot-web-central.appspot.com/web/

**Comment by PaulKinlan** [comment]
Many appologies for the time it took to getting around to reviewing this.

**Comment by PaulKinlan** [comment]
It will go live in the next major push that we do.

**Comment by rmacklin** [comment]
Thanks @PaulKinlan

**Pull request merged**
