### PR TITLE
translation mistakes

### PR DESCRIPTION
**Pull request by LeoCp**

### CODE REVIEW

**Comment by PaulKinlan** [comment]
@LeoCp thank you for the PR, I know it is only a small change but we do need the CLA to be signed before we can pull it it in :( sorry.

**Comment by LeoCp** [comment]
I signed it!

**Comment by PaulKinlan** [comment]
Why was this closed?

**Comment by PaulKinlan** [comment]
Ah. I think I see this in another pr

**Comment by LeoCp** [comment]
Hi @PaulKinlan, i did a new PR with more translations #3309.

**Pull request closed without merging**
