### PR TITLE
Changed media index.markdown and images/index.markdown

### PR DESCRIPTION
**Pull request by 2bchuck**
I've changed translation for 'media/index.markdown' to be read more naturally in Korean language. And add translated in Korean for 'images/index.markdown'.

### CODE REVIEW

**Comment by petele** [comment]
@2bchuck - can you please check on the CLA? before I can merge this it needs to have a CLA: yes label.  Thanks!

**Comment by 2bchuck** [comment]
I did it then, my main email for GitHub was hotmail one. I changed my
primary mail to gmail which was checked yes on he CLA. I'm doing next one.
I thought that'll be clear when I pull request my next one. Or I'll figure
out for ky secondary email CLA checking. Thanks.
2015. 7. 17. 04:00에 "Pete LePage" <notifications@github.com>님이 작성:

**Comment by 2bchuck** [comment]
I,ve been trying to sign again since I'd found been used different email
for committing. Then I've got this message. "It looks like you've already
signed this CLA. If you'd like to edit your contact information, you may do
so below." So I added my alt mail as "gooranuba@hotmail.com" which was
email address been committed.
Can you check again?
Thank you.
2015. 7. 14. 오후 6:43에 "googlebot" <notifications@github.com>님이 작성:

**Comment by petele** [comment]
Hey @2bchuck - the CLA still doesn't look signed, and I'm not sure what's going on. I'm going to close this for now.

Unfortunately, we cannot accept contributions unless the CLA is properly signed. In addition, it looks like some of the content in this PR is only partly translated. We want to make sure that it's 100% translated before merging it so that developers don't get partially translated content.

Thanks,
PEte

**Pull request closed without merging**
