### PR TITLE
[Translation zh-tw] _common-links.md

### PR DESCRIPTION
**Pull request by agektmr**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/zh-TW/review/356)

### CODE REVIEW

**Comment by agektmr** [comment]
Reviewed by @limhenry translated by @kennith

**Comment by agektmr** [comment]
Comparing to [the original](https://github.com/google/WebFundamentals/blob/master/src/content/en/_common-links.md), it's missing

```
[service-worker-primer]: /web/fundamentals/getting-started/primers/service-workers "Service Workers: An Introduction"
```

Why is that?

**Comment by limhenry** [comment]
@agektmr weird, that line is not showing in gitlocalize: https://gitlocalize.com/repo/107/zh-TW/src/content/en/_common-links.md

**Comment by agektmr** [comment]
I think it's GitLocalize issue cc: @sotayamashita @chikathreesix

**Comment by sotayamashita** [comment]
@agektmr I have create a pull request to solve issue temporary. https://github.com/agektmr/WebFundamentals/pull/1

**Comment by agektmr** [comment]
@sotayamashita Thanks. The PR is merged.
We still have to sort CLA issue. Can you explain what is going on?

**Pull request merged**
