### PR TITLE
Add new content to add-breakpoints

### PR DESCRIPTION
**Pull request by kaycebasques**
review: @Meggin 

This is part of the content from my async JS draft. We agreed to scrap that doc and move any new content to existing documents.

Updates:
* New section: Break all XMLHttpRequests at given stage in event lifecycle
* New section: Break on uncaught exceptions
* Edit: Re-arranged the XMLHttpRequest section to flow better on account of new section

### CODE REVIEW

**Comment by petele** [comment]
@kaycebasques did @Meggin already review this, or is the review still required?

**Comment by Meggin** [comment]
I'm reviewing today.

**Comment by Meggin** [comment]
I sent Kayce a doc with review comments, as it has more discussions points.

**Comment by kaycebasques** [comment]
hallo @Meggin,

Updated per your feedback. Plz review.

**Comment by Meggin** [comment]
Great. I'll wrap up both reviews (started step through code review) and
this one before we meet tomorrow.

**Comment by PaulKinlan** [comment]
@Meggin is this good to go?

**Comment by kaycebasques** [comment]
Hi @PaulKinlan, @Meggin sent me a second round of minor edits, which I'll be incorporating tomorrow.

**Comment by PaulKinlan** [comment]
Perfect.

**Comment by Meggin** [comment]
FYI, review comments doc: https://docs.google.com/a/google.com/document/d/1BuV7nMLl1xpiaumPBVafh2HDn-i_Vuwhhm1xJUpC_go/edit?usp=sharing

**Comment by kaycebasques** [comment]
hallo @Meggin all set for review

**Pull request merged**
