### PR TITLE
Add translation zh-cn for render performance

### PR DESCRIPTION
**Pull request by simongong**

### CODE REVIEW

**Comment by chenxsan** [comment]
I once filed [this issue](https://github.com/google/WebFundamentals/issues/760) about translation convention, I'm not sure if there's one translation style guide now? @PaulKinlan. If not, then which style do this project prefer more? With white space between Chinese character and English word or without? I can see there are [white spaces between transitional Chinese and English word](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-tree-construction?hl=zh-tw). We better keep one style instead of two.

**Comment by PaulKinlan** [comment]
It seem's one space will be best.  Honestly, we haven't thought about it
too much.

**Comment by PaulKinlan** [comment]
I'll merge this and if we need to change we can.

**Comment by simongong** [comment]
@chenxsan @PaulKinlan 
As to the concern of `white space between mixing characters`, I vote for **one space** as well for the sake of better readability.
So I think it would be better to add a tip/guidance somewhere for future translation, especially for non-alphabet based languages.

**Pull request merged**
