### PR TITLE
[Translation zh-tw] _book.yaml

### PR DESCRIPTION
**Pull request by agektmr**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/zh-TW/review/358)

### CODE REVIEW

**Comment by agektmr** [comment]
Reviewed by @limhenry translated by @kennith

**Comment by sotayamashita** [comment]
We have signed Corporate CLA but it will takes time to accept a few days according FAQ for Google CLA. https://cla.developers.google.com/about

**Comment by petele** [comment]
Sadly, we can't localize `_book.yaml` or `toc.yaml` files.

**Comment by petele** [comment]
Due to the way DevSite works, localizing some files will cause some pretty serious headaches:
* `_book.yaml`, `_toc.yaml` or `_upper_tabs-*.yaml`
* `_project.yaml`

But, we can do `_footer.yaml`!

Sorry! :(

**Comment by sotayamashita** [comment]
@plete Oh. I got it. We will lock these files to avoid translating in GitLocalize.

**Comment by agektmr** [comment]
@sotayamashita how would that be possible from our side? Can we manipulate translatable/non-translatable directories/files?

**Comment by sotayamashita** [comment]
@agektmr 

> how would that be possible from our side?  
> Can we manipulate translatable/non-translatable directories/files?

We will implement a feature to ignore some file on GitLocalize. After implementing the feature, we will configure these file manually instead of you.

**Pull request closed without merging**
