### PR TITLE
Reds

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by petele** [comment]
Hey @jpmedley - is the new content launched on web.dev?

**Comment by jpmedley** [comment]
For quite some time.

**Review by petele — APPROVED** [review]

**Comment by beaufortfrancois** [comment]
> For quite some time.

It is not true. "Fast playback with video preload" is still not launched in web.dev.
See https://github.com/GoogleChrome/web.dev/pull/4064#pullrequestreview-523095197 for context.

**Comment by beaufortfrancois** [comment]
@jpmedley @petele Can we revert this PR?

**Comment by beaufortfrancois** [comment]
https://developers.google.com/web/fundamentals/media/recording-audio and https://developers.google.com/web/fundamentals/media/recording-video pages are now 404.

**Comment by beaufortfrancois** [comment]
@jpmedley @petele (gentle ping)

**Comment by jpmedley** [comment]
Sorry about that. I have a PR on my hard drive that I was having trouble pushing because of a false error. Pete and I got sidetracked before we could sort it.

**Comment by beaufortfrancois** [comment]
@jpmedley (gentle ping)

**Comment by jpmedley** [comment]
Pete and I got sidetracked on this. I have a local PR ready to fix this, but I can't push because the contributor files are missing. I've tried `npm run build`. It throws and undefined error on a variable named `primordials`.

**Comment by beaufortfrancois** [comment]
I've started restoring media articles at https://github.com/google/WebFundamentals/pull/9230. PTAL

**Comment by jpmedley** [comment]
Sorry about this. I tried to restore this a while ago, but ran into bugs
that were preventing me from pushing to origin. We never got back to fixing
it.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Pull request merged**
