### PR TITLE
Fixes #5126 - Updates image CRP analysis-dom-css-js-async.png

### LINKED ISSUE #5126: Flow diagram needs to be corrected
Hi,

Flow diagram on this page:
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/analyzing-crp

needs to be corrected in below image:
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/images/analysis-dom-css-js-async.png

to swap:
RUN JS <-> RENDER PAGE

### PR DESCRIPTION
**Pull request by ChathuminaVimukthi**
Corrected the flow diagram

### CODE REVIEW

**Comment by ChathuminaVimukthi** [comment]
I signed it!

**Comment by ChathuminaVimukthi** [comment]
Name of the above file is a bit different from the original file. I'm adding the file again with the correct name. 
analysis-dom-css-js-async

**Comment by ChathuminaVimukthi** [comment]
Deleted the specific file.

**Comment by petele** [comment]
Thanks for the fast turn around! Sorry to ask one more, the file went from 14K to 935K! Any way to get it back closer to its original size?

**Comment by ChathuminaVimukthi** [comment]
No problem :) I will make the file size smaller.
Happy to contribute!

**Comment by PaulKinlan** [comment]
Wait. Can we hold off on merging. I'd like to get @igrigorik and @addyosmani to chime in.

The async attribute still blocks onload, but not the creation of the CSSOM or DOM construction. I'd just like either Addy or Ilya to validate the intent of the original image vs this.

**Comment by ChathuminaVimukthi** [comment]
No problem at all :)

**Comment by igrigorik** [comment]
Is there a summary for what the intent is here? `<script async>` executes as soon as the fetch completes, so the existing diagram is not wrong. As Paul noted, the benefit of async is that it doesn't block DOM construction (which current diagram captures also), and rendering.. could happen anytime after we have both DOM + CSSOM.

**Comment by petele** [comment]
@ChathuminaVimukthi - can you address @igrigorik's comments.

**Comment by petele** [comment]
@ChathuminaVimukthi - any updates on this?

**Comment by ChathuminaVimukthi** [comment]
I understood the whole async thing by referring to igrigorik's comment and I agree with @igrigorik. It seems that both diagrams are correct. I think it is not necessary to merge my updated diagram :)

And sorry for the late reply.

**Pull request closed without merging**
