### PR TITLE
Payment Request API - Rejig

### PR DESCRIPTION
**Pull request by gauntface**
This PR is largely a place holder at the moment to enable numerous contributors work on a single source of truth for the next Payment Request Docs.

@petele + @agektmr can you confirm if this structure is ok with you?
@agektmr At the moment I've put your name against the FAQ of the merchants guide, is that ok with you?
@mustafa-x I've added a file for UX best practices for you (It's currently blank apart from your name ;) )
@afitz0 I've scheduled time with you tomorrow to see if you are interested in working on any of this
@zkoch as an FYI - need to sync on the Android + Web Payment Processor Side of this.

### CODE REVIEW

**Comment by agektmr** [comment]
Me on FAQ sounds good.
I'm also planning to write a basic guide for integrating with Payment Gateways where it also hosts list of available PGs. Can you add that?

**Comment by mustafa-x** [comment]
ill take a look later and see what I can do.

**Comment by gauntface** [comment]
@agektmr can you create a branch based off of this branch and then PR back into this branch?

**Comment by gauntface** [comment]
Going to close this given all the other individual PRs.

**Pull request closed without merging**
