### PR TITLE
[TRANSLATION] EN to JA: your-first-progressive-web-app/step-01,step-02

### PR DESCRIPTION
**Pull request by yoichiro**
I just translated two files `your-first-progressive-app/step-01.markdown` and `your-first-progressive-app/step-02.markdown` from EN to JA. It would be great if someone can confirm this PR and merge this diff to the master branch. Thank you in advance.

### CODE REVIEW

**Comment by yoichiro** [comment]
@agektmr Eiji-san, could you confirm/review this PR?

**Comment by agektmr** [comment]
LGTM

**Comment by yoichiro** [comment]
@agektmr Thank you, Eiji-san.
@PaulKinlan It would be great if you merge this PR. Thank you!

**Comment by yoichiro** [comment]
@PaulKinlan Thank you!

**Pull request merged**
