### PR TITLE
[Translation] Translated ud891.html into Simplified Chinese

### PR DESCRIPTION
**Pull request by chikathreesix**
@limhenry translated this file on GitLocalize. Create a pull request on behalf of him.

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/zh-CN/review/284)

### CODE REVIEW

**Comment by chikathreesix** [comment]
I signed it!

**Comment by chikathreesix** [comment]
Hi @limhenry, I have created a pull request from GitLocalize since your review request hasn't been reviewed for a while. But the problem is, it seems that I need your confirmation. Could you check this, please?

**Comment by limhenry** [comment]
@chikathreesix yes, the PR is OK for me 😄 

cc @agektmr

**Comment by agektmr** [comment]
@chikathreesix Does this mean there needs to be an admin to send a Pull Request on GitLocalize on behalf of a translator?

**Comment by chikathreesix** [comment]
@agektmr Not only admins but also language moderators can send a pull request on GitLocalize.

**Comment by petele** [comment]
I'll merge for now, but we should figure out a better way to handle this since the CLA chain becomes painful otherwise.

**Comment by petele** [comment]
CLA - chain OK.

**Comment by sotayamashita** [comment]
@petele 

> I'll merge for now, but we should figure out a better way to handle this since the CLA chain becomes painful otherwise.

Do you have any idea?

**Comment by agektmr** [comment]
@chikathreesix That sounds like we need at least one person admin/moderator taking care of a language, right? That's ideal in a long term, but not a short term.

**Comment by agektmr** [comment]
@sotayamashita I'm happy to take care of this at least until we figure out a better solution.

**Comment by chikathreesix** [comment]
@agektmr Yes, correct. Actually, that's what I was considering as well. If it's difficult to assign someone as a moderator for now, in this case, it might be better to send a pull request directly from GitLocalize (not through review request)

**Pull request merged**
