### PR TITLE
Translated push notification tutorial step-4 in Korean

### PR DESCRIPTION
**Pull request by joshua1988**
Translated push notification tutorial step-4 in Korean

### CODE REVIEW

**Comment by petele** [comment]
hey @joshua1988 - would you mind starting to work in the next-version branch instead of master? We're moving to a new infrastructure and would love to have your stuff there. I expect it to launch mid to late September. 

Instead of having a huge & painful build process, files are generated at request time, and I expect development will be faster and easier. The readme is up to date, but if you run into problems, let me know!

**Comment by joshua1988** [comment]
@petele - Gotcha, I will take a look at the readme file and see how it works. Will also let you know if I encounter any problems! Thanks!

P.S : You are talking about this process right?

image

**Comment by cwdoh** [comment]
Awesome. New process make us concentrating translation instead of pulling update stuffs. :+1:

**Comment by cwdoh** [comment]
@joshua1989 now we can attach stagin site url for requesting review to other translators. :)

**Comment by joshua1988** [comment]
@cwdoh - sounds good to me! I am having a really hard time to prepare the working set for the next branch that Pete suggested...

**Comment by cwdoh** [comment]
If you need any help, just let me know. I'll cross over the road. :)

2016년 8월 30일 (화) 오후 9:05, Josh Jang <notifications@github.com>님이 작성:

**Pull request merged**
