### PR TITLE
Translated optimize-encoding-and-transfer EN to KO

### PR DESCRIPTION
**Pull request by joshua1988**
My first translation work

### CODE REVIEW

**Comment by petele** [comment]
@joshua1988 - looks like this isn't building, can you please take a look. And can you also add a description about what this does?

**Comment by petele** [comment]
Hey @joshua1988 - thanks for the pull request. I've closed the other commits and will keep stuff in this one. For some reason the build failed, and I've kicked off a new one.

**Comment by joshua1988** [comment]
Hey @petele - Thanks for cluttering up my mistakes. I am pretty new to contributing an open repository but I am really excited about this contribution as a translator. I will keep up my work! Please help me out! :)

Josh

**Comment by cwdoh** [comment]
@joshua1988, lgtm with addressing nits:

* `자원`을 발음 그대로 `리소스`로 하시는 것은 어떨지? 개인적으로는 개발자에게는 그쪽이 더 자연스러운 것 같아요. 
* 몇몇 문장에 조사가 빠져있네요. :)

**Comment by joshua1988** [comment]
@cwdoh 네 감사합니다! 앞으로 번역시에 참고하도록 할게요 :)

**Comment by joshua1988** [comment]
@petele - I finally managed to make it right. Should I make another pull request to put this contents in the repository? I am wondering if your "DO NOT MERGE" label means to close this section down.

**Comment by joshua1988** [comment]
@petele - Thanks for helping me out!

**Pull request merged**
