### PR TITLE
Content layout/typo optimizations

### PR DESCRIPTION
**Pull request by pbakaus**
These are small, but powerful optimizations that improve the look and feel across Web Fundamentals. Explanation:

 - no margin on li's: They usually don't have them, and this has been blowing up list-heavy pages like crazy.
 - no letter spacing: Removed letter spacing from three places where they've been used. Weirdly, they come from MDL, yet in the Material Design spec, I couldn't find any note about letter spacing. Letter spacing is arguably a bad idea, as it messes with the font and decreases readability, and should be reserved for big, bold headings.
- The indentation of the second level in the nav drawer was redundant, as the title above from the first level nav is already bold, suggesting it's the title. W3C Specs have been doing something similar, [looking quite nice](https://drafts.css-houdini.org/worklets/).  This gives us a few much needed horizontal pixels back.

**Before:**
before

**After**
after

@petele and @gauntface, would be awesome if you could take a look.

### CODE REVIEW

**Comment by pbakaus** [comment]
cc @paulirish (we've discussed some of these this morning)

**Comment by paulirish** [comment]
+1 these

the letter spacing in particular really threw me for a loop.

**Comment by petele** [comment]
In general I like most of the changes here, but it looks like there were a few side effects that need to be accounted for...

* Double line when there's no content in some pages [example](https://pr-2649-dot-weasel-dot-web-central.appspot.com/web/fundamentals/design-and-ui/browser-customization/)
* Landing page lists are a bit too tight [example](https://pr-2649-dot-weasel-dot-web-central.appspot.com/web/fundamentals/design-and-ui/?hl=en)
* Other lists are too tight [example](https://pr-2649-dot-weasel-dot-web-central.appspot.com/web/fundamentals/discovery-and-monetization/search-optimization/url-structure?hl=en)

Before we merge I'd like to see these kinds of issues address. Or split this into two PRs, one for letter spacing and one for li's.

**Comment by pbakaus** [comment]
Thanks for finding these Pete! I fixed 1 and 2, but 3 is hard as there is no "right" solution for all scenarios: Without margin, the list items look a little tight when they have multiple lines of text, but with margin, the look bad in most other scenarios.

I've checked out some other pages like Smashing Mag and List Apart, and they all have margins but 1/3 less than what we had. I'll play around with it and update this PR so you can take a look.

**Comment by pbakaus** [comment]
Oh just saw you merged, ok will do another PR and address 3) in that one ;)

**Pull request merged**
