### PR TITLE
Remove duplicated native install code snippet

### PR DESCRIPTION
**Pull request by mahemoff**
Maybe I missed something, but seems like there was some unnecessarily redundant duplication here.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
I added this in so people can just copy and paste if they don't want the normal part of the manifest.

**Comment by mahemoff** [comment]
I see exactly the same code block twice on https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android#native

By "normal" I think you mean the one for web app, ie you mean you wanted to explicitly show the native snippet. Which I agree is good, but I think you've done so twice.

**Comment by PaulKinlan** [comment]
There are extra curly braces in the second one.

**Comment by mahemoff** [comment]
I see. I did miss them. So I think you're saying that the second example is the whole manifest file - that part wasn't so clear from the preamble.

**Comment by PaulKinlan** [comment]
Yes. I will clear this up though.

**Pull request closed without merging**
