### PR TITLE
Add updates to PWA architecture

### PR DESCRIPTION
**Pull request by addyosmani**
This is the PR for PWA Architecture under /web/fundamentals/progressive-web-apps/architecture. I've updated this draft to try addressing @petele's feedback from the original review. 

Some of Joe's feedback has been addressed, but I think there are overall flow/simplification improvements that could be made. If @jpmedley has time, perhaps this could be tackled separately next (sep PR)?

**Assorted notes:**
- Once this PR lands we will want to also look at what redirects/changes are needed for the PWA>Overview in our TOC to redirect to the current overview content. 
- This PR was intentionally trying to stick pretty close to the structure of the ILT course content with fixes. It's long as is and I didn't want to include a walk-through of https://github.com/GoogleChrome/application-shell. We might do this in follow-up future work.

### CODE REVIEW

**Comment by petele** [comment]
@jpmedley - don't bother looking yet, still in flux.

**Comment by addyosmani** [comment]
@petele The restructuring you've proposed looks good to me. Summarizing our last convo:

- [ ] Simplify large walls of text where we can (add images, lists etc to make it welcoming)
- [ ] Migrating needs 3-4 hours of work to properly fill it out
- [ ] Architecting: yank out content that better belongs in a codelab. Focus on what folks need to know

Given there are now effectively two doc in here, would you prefer me to flesh out two separate PRs for this content? (aim to get migration in a land-worthy state this week, architecture next). Or keep both in one PR?

**Comment by petele** [comment]
@addyosmani - I think two separate PRs make sense, will be easier to land it that way.

**Comment by addyosmani** [comment]
Sounds good. I've been taking a detour to flesh out #3459 but will be jumping back on this next.

**Comment by petele** [comment]
@addyosmani - please assign to me when this is ready to go.

**Comment by addyosmani** [comment]
Closing in favor of a new PR for each of these other parts.

**Pull request closed without merging**
