### PR TITLE
Fix DevTools nits

### PR DESCRIPTION
**Pull request by beaufortfrancois**
I was reading awesome DevTools doc and found out some minor issues.

@kaycebasques 

[WF_IGNORE:BLINK]

### CODE REVIEW

**Comment by petele** [comment]
@kaycebasques - merge at will!

**Comment by beaufortfrancois** [comment]
@petele What is going on? I can't merge and the Travis CI Build has been in progress for 11 hours ;(

**Comment by PaulKinlan** [comment]
Kinlan hammer invoked.

**Comment by beaufortfrancois** [comment]
Merci Monsieur @PaulKinlan!

**Pull request merged**
