### PR TITLE
Add `prefers-color-scheme` article

### PR DESCRIPTION
**Pull request by tomayac**
- Add the `prefers-color-scheme` article

**Target Live Date:** Draft, do not merge yet!

- [ ] This has been reviewed and approved by (NAME)
- [X] I have run `npm test` locally and all tests pass.
- [X] I have added the appropriate `type-something` label.
- [X] I've staged the site and manually verified that my content displays correctly.

### CODE REVIEW

**Comment by petele** [comment]
When this is ready for merging, remove the DO NOT MERGE tag.

**Comment by tomayac** [comment]
Sure thing. It’s also one of their new [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/), the “do not merge” is implicit.

**Comment by petele** [comment]
>  It’s also one of their new [draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/), the “do not merge” is implicit.

Yah, I saw that, but it doesn't stand out as nicely, when I'm skimming the list of PRs, I can easily skip anything with a big, red DO NOT MERGE label, I have to look for the "Draft" text in small letters.

**Comment by tomayac** [comment]
Closing this PR here in favor of https://github.com/GoogleChrome/web.dev/pull/929, as per a conversation with @robdodson.

**Pull request closed without merging**
