### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nhantdn**
Fix hyperlink syntax

### CODE REVIEW

**Comment by nhantdn** [comment]
I signed it!

**Comment by petele** [comment]
Hey @nhantdn - I just checked and it's not seeing your CLA. Would you mind going back to the site and resigning please?

**Comment by nhantdn** [comment]
Hi @petele, I already signed the CLA, somehow it doesn't work.
In my GitHub settings, I checked **Keep my email address private**, does it affect the signing process? Do I have to change signing email to GitHub's `@users.noreply.github.com` address?

**Comment by nhantdn** [comment]
It's alright now.

**Comment by petele** [comment]
Thanks for signing again or even just replying. Once in a while, Googlebot just needs a little nudge.

**Pull request merged**
