### PR TITLE
Updating code to fix the Lab

### PR DESCRIPTION
**Pull request by antoinebisch**
What's changed, or what was fixed?
- Adding workboxSW.precaching.precacheAndRoute([]); to service-worker.js for Workbox to function (Webpacks still uses workboxSW.precache([]);)
- Replacing staticFileGlobs by globPatterns for Gulp serve to function

**CC:** @petele

### CODE REVIEW

**Comment by petele** [comment]
@nasearle - can you review and migrate these changes into the Google doc source please? Once you've made the updates, please reply to this PR and I'll export and publish.

@antoinebisch - the source of truth for these docs is actually an internal Google doc. We'll make the changes there then update in a separate PR.

**Comment by petele** [comment]
@antoinebisch - btw: Thank you for the PR!!

**Comment by antoinebisch** [comment]
No problem. Thanks you!




<https://www.google.com/doodles/44th-anniversary-of-the-birth-of-hip-hop>


*  •  **Antoine Bisch*
*  •  *Mobile Solutions Consultant
*  •  *1-13 St Giles High Street, WC2H 8AG, London
  •  antoinebisch@google.com

<antoinebisch@google.com>


This email may be confidential and privileged. If you received this
communication by mistake, please don't forward it to anyone else, please
erase all copies and attachments, and please let me know that it has gone
to the wrong person.

The above terms reflect a potential business arrangement, are provided
solely as a basis for further discussion, and are not intended to be and do
not constitute a legally binding obligation. No legally binding obligations
will be created, implied, or inferred until an agreement in final form is
executed in writing by all parties involved.

**Comment by DavidScales** [comment]
@antoinebisch Thanks for the catch! 

@petele @nasearle  We've actually updated this lab & just about all of the others for v2 of the ILT content (& v3 of Workbox). We just haven't merged & published yet. We will check our status today and see about publishing a bunch of stuff :)

**Comment by nasearle** [comment]
+1 to what David said. We'll get back to you about publishing the docs soon. Thanks!

**Comment by DavidScales** [comment]
@antoinebisch @petele just to follow up, @nasearle and I are waiting for a green light to publish changes, as coordination needs to happen with instructors that use these materials. We will keep you posted

**Comment by nasearle** [comment]
@petele We have updated the source doc. Ready to publish. Thanks!

**Comment by nasearle** [comment]
And I see that it's published. Thanks all!

**Pull request closed without merging**
