### PR TITLE
Added missing verb

### PR DESCRIPTION
**Pull request by Svenmay**
IMHO there is a verb missing in the sentence "...but you won't be able to which interactions occurred....".

What's changed, or what was fixed?
- Added verb "tell" into the sentence.

**CC:** @petele

### CODE REVIEW

**Comment by petele** [comment]
@jeffposnick & @philipwalton - not sure if these docs are generated from the Workbox git repo, or if they come from ours. Can you figure it out and fix? Thanks!

**Comment by philipwalton** [comment]
Thanks @Svenmay for spotting and fixing this!

**Comment by ahtee** [comment]
Any update on where these docs are generated/coming from?

**Comment by jeffposnick** [comment]
Everything under https://github.com/google/WebFundamentals/tree/master/src/content/en/tools/workbox/reference-docs is auto-generated from the JSDoc present in the Workbox source code, using the scripts found in https://github.com/google/WebFundamentals/tree/master/gulp-tasks/workbox. Whenever we cut a new release of Workbox, we need to manually run those scripts and then commit the updated docs to this WebFundamentals repo.

Everything *not* under https://github.com/google/WebFundamentals/tree/master/src/content/en/tools/workbox/reference-docs is manually written and committed directly to this WebFundamentals repo.

**Pull request merged**
