### PR TITLE
Redirects batch 7

### PR DESCRIPTION
**Pull request by mattletford**
from: /web/updates/2011/08/Saving-generated-files-on-the-client-side
to: https://web.dev/browser-fs-access/

from: /web/updates/2018/08/chrome-ux-report-dashboard
to: https://web.dev/chrome-ux-report-data-studio-dashboard/

from: /web/fundamentals/primers/service-workers/high-performance-loading
to: https://developer.chrome.com/docs/workbox/caching-strategies-overview/

from: /web/fundamentals/primers/service-workers/lifecycle
to: https://developer.chrome.com/docs/workbox/service-worker-lifecycle/

@rachelandrew

### CODE REVIEW

**Review by rachelandrew — APPROVED** [review]

**Comment by rachelandrew** [comment]
@mattletford please resolve conflicts

**Comment by mattletford** [comment]
@rachelandrew conflicts resolved

**Comment by rachelandrew** [comment]
@mattletford it looks to still have conficts.

**Comment by mattletford** [comment]
@rachelandrew conflicts resolved

**Comment by kaczor6418** [comment]
This PR caused this issue:
https://github.com/GoogleChrome/developer.chrome.com/issues/2291

Now I cannot redirect to old article about service worker life-cycles

**Pull request merged**
