### PR TITLE
Language enhancements + title adjustment aka fixing #1041

### LINKED ISSUE #1041: Feedback for: /fundamentals/performance/index.html
Russian version of this page looks corrupted

Screenshot: http://dl1.joxi.net/drive/0004/1528/284152/141211/3831c398ad.jpg

Looks like decreasing the font size will fix the problem.

### PR DESCRIPTION
**Pull request by denpatin**
* Fixed #1041 
* Eliminated grammatical errors
* Improved language stylistics

### CODE REVIEW

**Comment by denpatin** [comment]
Was:
image from the issue #1041

Now:
screen shot 2015-01-05 at 4 49 45 am

**Comment by PaulKinlan** [comment]
Please sign CLA at https://developers.google.com/open-source/cla/individual

**Comment by denpatin** [comment]
@PaulKinlan Already signed: https://github.com/google/WebFundamentals/pull/1067#issuecomment-68643346
That's weird that the CLA tool doesn't say I've done it.

**Comment by PaulKinlan** [comment]
Yeah, the not that checks it is broken. I am disabling it today.

**Comment by PaulKinlan** [comment]
@denpatin there was a big change after this PR came in, sorry.  Can you update it so I can merge it in. Thanks

**Comment by denpatin** [comment]
Done.

**Pull request closed without merging**
