### PR TITLE
Rearranged things.

### PR DESCRIPTION
**Pull request by wibblymat**
- Translations separated into a path of their own
- Moved dot files up to the root
- Moved appengine path up to the root

### CODE REVIEW

**Comment by PaulKinlan** [comment]
@wibblymat looks like a re-basing is in order.

**Comment by wibblymat** [comment]
Rebasing always makes me sad. Why do all of the other commits now show up in this PR? The diff is now totally impossible to understand :(

**Comment by wibblymat** [comment]
Ok, managed to sort it out. I have split the PR into separate commits so that it is possible to review the code changes (by looking at just the third commit) without the file moves drowning everything out.

**Comment by wibblymat** [comment]
Fixes #997, in case anyone is wondering why I bothered.

**Comment by PaulKinlan** [comment]
Thanks bud.

**Pull request merged**
