### PR TITLE
Material branch

### PR DESCRIPTION
**Pull request by paullewis**
R @PaulKinlan

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Looks good.  Will merge.

**Comment by PaulKinlan** [comment]
cc @petele @gauntface will need a content push today :) also lots more going in.

**Comment by PaulKinlan** [comment]
as a side note, I want everyone on the team to be able to do the push as needed when we are all happy.

**Comment by petele** [comment]
Sounds good, it'll be a matter of adding the right people to the owners
file, then ensuring the docs are great.

PEte

On Thu, Oct 15, 2015 at 4:15 AM, Paul Kinlan <notifications@github.com>
wrote:

> as a side note, I want everyone on the team to be able to do the push as
> needed when we are all happy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/WebFundamentals/pull/2122#issuecomment-148355653>
> .
>



-- 

Pete LePage | Developer Advocate | petele@google.com | 650-733-6404

**Pull request merged**
