### PR TITLE
Italian translation contributions

### PR DESCRIPTION
**Pull request by lucab85**
1. newest Italian translation of: 
   * all Udacity courses (`ud811`, `ud860`, `ud882`, `ud891` & `ud890`, `ud892`, `ud893`, `ud899`)
   * `Performance`
   * `Performance > HTTP2`
   * `Performance > RAIL`
   * `Performance > Understanding Low Bandwidth and High Latency`
1. proof-read Italian translation of:
   * `Performance > Optimizing Content Efficiency`
   * `Performance > Critical Rendering Path`
   * `Media > Video`
1. added me as "translator"

### CODE REVIEW

**Comment by kosamari** [comment]
Hey ya! @lucab85, thank you for the PR. 
I'll have to wait for @petele to come back from vacation to merge translation, please be patient with us. Thank you :)

**Comment by lucab85** [comment]
Thank you for your message. I'll wait the lucky @petele.

**Comment by lucab85** [comment]
Hi @petele! Do you have reviewed my contribution? If you like this work I look forward for contribute more.

**Comment by petele** [comment]
hey @lucab85 - sorry, with Google I/O this week, I've been super swamped, I'll take a peek first thing next week!

**Comment by petele** [comment]
Hey @lucab85 - sorry this is taking so long. Before we can merge, I need to get a someone who speaks Italian to verify and proof it, and I haven't been able to line anyone up yet.

**Comment by lucab85** [comment]
I perfectly understand your company policy but, if is not a problem for you, I'll continue to give my contribution.

**Pull request closed without merging**
