### PR TITLE
fix: checkout created new local branch

### PR DESCRIPTION
**Pull request by teachtyler**
`git checkout -b code-lab` created a new branch from master for me locally, after deleting the folder and re-cloning I excluded `-b` and it switched fine. This might be specific to me.

### CODE REVIEW

**Comment by teachtyler** [comment]
I signed it!

**Comment by jpmedley** [comment]
@teachtyler 

Before I merge I want to understand your issue. The instruction is to switch to a branch called code-lab, which hasn't been previously created. the -b switch is what creates the code-lab branch. 

My question is, what made you think the result was incorrect?

(I think I know what the problem is already. Please humor me.)

Thanks

**Comment by teachtyler** [comment]
>which hasn't been previously created

https://github.com/GoogleChrome/airhorn/tree/code-lab
Switching to this is better than creating a new one, right?

>I think I know what the problem is already

https://xkcd.com/1597/

**Comment by Garbee** [comment]
An alternate solution might be `-B` instead of outright removing it. This flag will use an existing branch (and reset it) if found, otherwise it will create the branch.

**Pull request merged**
