### PR TITLE
Save-Data post for web updates

### PR DESCRIPTION
**Pull request by igrigorik**
@PaulKinlan @petele please take a look!

### CODE REVIEW

**Comment by jpmedley** [comment]
@petele I'm giving this a quick copy edit.

**Comment by igrigorik** [comment]
\o/ - thanks guys!

@petele when will this go live?

**Comment by petele** [comment]
I'm going to push Monday morning around 10am ET so that it's fresh for next
week, though happy to push earlier if you'd prefer.

PEte

On Fri, Feb 19, 2016 at 1:52 PM, Ilya Grigorik <notifications@github.com>
wrote:

> \o/ - thanks guys!
>
> @petele <https://github.com/petele> when will this go live?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/WebFundamentals/pull/2573#issuecomment-186359574>
> .
>



-- 

Pete LePage | Developer Advocate | petele@google.com | 650-733-6404

**Comment by igrigorik** [comment]
Monday is good -- thanks Pete!

**Comment by PaulKinlan** [comment]
\o/**\o/

**Pull request merged**
