### PR TITLE
Add Feature Policy for Autoplay

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Live preview at https://pr-5364-dot-web-central.appspot.com/web/updates/2017/09/autoplay-policy-changes

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
I've added a note about the experimental flag.
Does that still look good to you @mounirlamouri @rebeccahughes?

If so, I'll publish this.

**Comment by rebeccahughes** [comment]
There is also a "Feature Policy for Autoplay" flag but it is still in Gerrit (http://crrev.com/c/800050)

**Comment by beaufortfrancois** [comment]
And here it is @rebeccahughes: https://github.com/google/WebFundamentals/pull/5364/commits/72f73e513e4191c2d3a79967be5adc39b51df42f
We'll wait for [http://crrev.com/c/800050](http://crrev.com/c/800050) to land and we'll push this article update.

**Comment by beaufortfrancois** [comment]
@petele We're good to go. You can merge and push live

**Pull request merged**
