### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by lucab85**
Minor typo fixes

### CODE REVIEW

**Comment by petele** [comment]
@lucab85 - can you pull the workbox stuff out of this PR? I believe that stuff is being pulled from a separate repo. @gauntface can confirm.

**Comment by lucab85** [comment]
Conflicts resolved. Waiting for @gauntface

**Comment by gauntface** [comment]
No it's all in this repo.

**Comment by gauntface** [comment]
@lucab85 thanks for doing this, really appreciate it!

**Pull request merged**
