### PR TITLE
Add redirects for new media section.

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by dr-streur** [comment]
passing thru 🔥 🐇

**Review by petele — CHANGES_REQUESTED** [review]
Hey @jpmedley - in order for redirects to work, you need to delete the source content. Can you update this PR and delete the content (including all languages) from WebFu?

**Comment by jpmedley** [comment]
I'm getting merge conflicts related to the files I deleted. I'm not sure why.

**Comment by jpmedley** [comment]
I'm not sure what to do. Everything I've tried to resolve these conflicts creates more problems than there are conflicts.

**Comment by jpmedley** [comment]
@petele I tried making a new PR. I'm still getting these warnings. I don't why. I searched on the warning message. The only hits on all of google or this pr and another one for this site from 2017.

**Comment by jpmedley** [comment]
If you want to experiment with this, here's the more recent PR: #9053

**Pull request closed without merging**
