### PR TITLE
Spell error

### PR DESCRIPTION
**Pull request by bhargav175**

### CODE REVIEW

**Comment by bhargav175** [comment]
I signed it!

**Comment by PaulKinlan** [comment]
I actually think shaving was the intended word here

**Comment by bhargav175** [comment]
Idk. Never heard a phrase like that before. Feel free to decline the PR if 'shaving' is the intended word.

**Comment by gauntface** [comment]
cc @jakearchibald any opinion on 'shaving' vs 'saving'

**Pull request closed without merging**
