### PR TITLE
Designer vs developer podcast ep03

### PR DESCRIPTION
**Pull request by mustafa-x**
Can we merge this on Friday? I am away so will have difficulty making edits as I don't have access to my laptop.

### CODE REVIEW

**Comment by jpmedley** [comment]
@mustafa-x This is post-dated. I assume we shouldn't merge and push live until Monday.

**Comment by mustafa-x** [comment]
If that is possible, yes, Monday would be fantastic :) I plan on publishing an article that will link to the new pages on Tuesday but usually i push stuff on Friday to make sure it doesn't slip through as I am forgetful :)

**Comment by mustafa-x** [comment]
@jpmedley @petele is it ok to push this live? I am not sure if any other branches have been merged since this PR, I currently dont have access to the code, as on holiday with no laptop :(

**Comment by jpmedley** [comment]
@mustafa-x I'll push this morning.

**Pull request merged**
