### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by jeffposnick** [comment]
@jpmedley—I'm only able to add comments on lines that have changed in this PR, which is basically only the lines with dates in them. There's no option for commenting on the lines that remain the same.

**Comment by jeffposnick** [comment]
I went through deleting/readding the content in some branches in my fork, and put together a PR that I can comment on: https://github.com/jeffposnick/WebFundamentals/pull/1

**Comment by jakearchibald** [comment]
@jeffposnick cheers! I'll also comment on that one

**Comment by jakearchibald** [comment]
What order are people expected to read these?

**Comment by petele** [comment]
@jpmedley can we close this now?

**Pull request closed without merging**
