### PR TITLE
Several language enhancements + title translations

### PR DESCRIPTION
**Pull request by denpatin**
* Substituted hyphens to dashes
* Shortened double spaces
* Translated remaining titles

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Please sign CLA at https://developers.google.com/open-source/cla/individual

**Comment by denpatin** [comment]
Done.

**Comment by PaulKinlan** [comment]
@denpatin the CLA tool might say you are still not, don't worry about it.  I will look at merging this now.

**Comment by denpatin** [comment]
Don't know why doesn't the CLA tool say I signed it:
screen shot 2015-01-04 at 9 34 52 pm
Maybe I should sign something else?

**Comment by PaulKinlan** [comment]
It's ok, the tool currently looks at the wrong database.

**Pull request merged**
