### PR TITLE
[lighthouse] move references to audits/ and add ToC

### PR DESCRIPTION
**Pull request by kaycebasques**
@petele this is good to go unless you or @jpmedley have any requests

### CODE REVIEW

**Comment by jpmedley** [comment]
@kaycebasques Do you need to keep audits/template.md longterm? It's making the tests fail.

**Comment by petele** [comment]
@kaycebasques - back to you, there are some build failures that need to be corrected.

**Comment by kaycebasques** [comment]
I didn't know the CI system was hooked up to `next-version` o_O

I fix yes

**Comment by kaycebasques** [comment]
@jpmedley ya... I'd prefer to have the template live with the docs

**Comment by kaycebasques** [comment]
@petele build is happy

**Pull request merged**
