### PR TITLE
Improved Code Syntax readibility

### PR DESCRIPTION
**Pull request by beaufortfrancois**
I find it really hard to read code snippets on my mobile phone so I decided to change it. 
Please let me know what you think.

R=@petele

**DESKTOP BEFORE**
---

screenshot 2016-01-22 at 10 14 53 am

**DESKTOP AFTER**
---
screenshot 2016-01-22 at 10 14 44 am

**MOBILE BEFORE**
---

screenshot_20160122-101617

**MOBILE AFTER**
---

screenshot_20160122-101541

### CODE REVIEW

**Comment by ebidel** [comment]
Can we also bump the general line-height on codeblocks? I noticed lines are very mushed together when writing an article.

**Comment by PaulKinlan** [comment]
cc @gauntface

**Comment by beaufortfrancois** [comment]
Thanks @ebidel for the feedback! I've updated my patch:

```diff
diff --git a/src/static/styles/partials/_base.scss b/src/static/styles/partials/_base.scss
index c6dd431..5f3825c 100644
--- a/src/static/styles/partials/_base.scss
+++ b/src/static/styles/partials/_base.scss
@@ -88,6 +88,7 @@ pre {
 
 pre, code {
   font-size: 10pt;
+  line-height: $base-line;
   word-wrap: normal;
   font-family: 'Roboto Mono', 'Inconsolata', 'monospace';
 }

**Comment by beaufortfrancois** [comment]
Here's how it looks like now:
screenshot 2016-01-25 at 10 28 22 am

**Comment by PaulKinlan** [comment]
LGTM.

**Comment by beaufortfrancois** [comment]
Can we also update live site?

**Comment by PaulKinlan** [comment]
We have to do a deploy.

**Pull request merged**
