### PR TITLE
Finishes S2 of HTTP 203; adds S3

### PR DESCRIPTION
**Pull request by paullewis**
PTAL @gauntface @petele

### CODE REVIEW

**Comment by PaulKinlan** [comment]
@gauntface don't we auto generate all this stuff now?

**Comment by gauntface** [comment]
No we don't auto generate this.

Can't come up with a way to accommodates everything. For example, if we autogenerated everything, how would podcasts sit with all of this?

**Comment by PaulKinlan** [comment]
Right, but this isn't the podcast... not bothered either way really just that I know we argued about it.

**Comment by gauntface** [comment]
Yeah it's hard. I have a gulp task that is a GUI for creating show series
and pages

**Comment by paullewis** [comment]
Actually it's not the podcast; that's going to be a separate PR. This is just for the video content.

**Comment by gauntface** [comment]
Podcast was just an example that makes auto-generation difficult - that was all :)

**Pull request merged**
