### PR TITLE
[Translation zh-cn] Updates > 2017 > 09 > Sensors For The Web!

### PR DESCRIPTION
**Pull request by Honry**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/875/zh/review/675)

@limhenry, PTAL.

### CODE REVIEW

**Comment by Honry** [comment]
I signed it!

**Comment by limhenry** [comment]
@agektmr I reviewed this. You may merge this PR. 😄 

_Anyway, something wrong with the CLA?_

**Comment by Honry** [comment]
@limhenry, I just sign the CLA, maybe it needs some time to be activated.

BTW, the Travis CI fails with error: `ERROR: src/data/_contributors.yaml Zasada came before Lin`, 
do u know how to fix it?

**Comment by Honry** [comment]
> BTW, the Travis CI fails with error: ERROR: src/data/_contributors.yaml Zasada came before Lin,
do u know how to fix it?

I found the answer. :-)

**Comment by Honry** [comment]
Thank you! @petele, @limhenry

**Pull request merged**
