### PR TITLE
[KO] Translation of layoutNG.md

### PR DESCRIPTION
**Pull request by yt-alconost**
This translation has passed a high-level review by Alconost.

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/ko/review/8925)

### CODE REVIEW

**Comment by petele** [comment]
Hi @yt-alconost, can you please provide a more detailed description of what's included in this PR? Please update the title and description. "Acceptable" doesn't tell me about what this is.

Also, can you make sure you've signed the CLA please?

**Comment by agektmr** [comment]
@ilyaspiridonov Can you answer @petele 's question?

**Comment by yt-alconost** [comment]
@googlebot I signed it!

**Comment by yt-alconost** [comment]
@seonyeong Hello, can you please verify your consent by commenting '@googlebot I consent' 
Thank you!

**Comment by yt-alconost** [comment]
@agektmr Apart from the CLA issue, this one is good to be merged.

**Comment by yeong9** [comment]
@googlebot i consent 😃

**Comment by yeong9** [comment]
@googlebot I consent.

**Pull request merged**
