### PR TITLE
update contributor info - henrylim

### PR DESCRIPTION
**Pull request by limhenry**

### CODE REVIEW

**Comment by agektmr** [comment]
@mathiasbynens We are seeing OAuth failure in Travis. Do you know how to fix this?

**Comment by mathiasbynens** [comment]
The failure seems unrelated to this change. I’ve just restarted the build.

**Comment by mathiasbynens** [comment]
cc @petele `addCommitComment.js` is failing. Any ideas?

**Comment by PaulKinlan** [comment]
This failure is only seen on remote branches. We can only stage and test properly for changes directly in a branch on the repo.

**Pull request merged**
