### PR TITLE
Update ShadowDom/index.md

### PR DESCRIPTION
**Pull request by Servuc**
Great post !!! I don't know this feature ! Just, one missed = on line 103

### CODE REVIEW

**Comment by Servuc** [comment]
I signed it!

**Comment by ebidel** [comment]
Thanks for the PR! Our CLA bot wasn't able to find your github username. Did you sign it with "Servuc"?

**Comment by Servuc** [comment]
You're welcome ;)

Yes, I've only this account on Github/Google and informations on https://cla.developers.google.com/clas seem good. Strange.

**Comment by ebidel** [comment]
Looks good now!

**Pull request merged**
