### PR TITLE
[Translate ru] Resources -> translations

### PR DESCRIPTION
**Pull request by DmitrySkripunov**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/ru/review/336)

### CODE REVIEW

**Comment by DmitrySkripunov** [comment]
@petele sorry, but ping)

**Comment by petele** [comment]
Hey @DmitrySkripunov - I'm looking for a second reviewer to do a quick once over. Hopefully I'll find one in the next couple of days!

**Comment by Ann40a** [comment]
@petele are you looking for a specific person from project maintainers? Otherwise I can take a look at this translation (I'm Russian native speaker).

**Comment by ilyaspiridonov** [comment]
@agektmr Reviewed

**Pull request merged**
