### PR TITLE
[Translation zh-tw] upper_tabs-Fundamentals.yaml

### PR DESCRIPTION
**Pull request by agektmr**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/zh-TW/review/345)

### CODE REVIEW

**Comment by agektmr** [comment]
Reviewed by @limhenry translated by @kennith

**Comment by agektmr** [comment]
@kennith can you sign CLA?

**Comment by agektmr** [comment]
@kennith wait, you should have already signed. Perhaps missing signature in the commit?
@sotayamashita @chikathreesix

**Comment by kennith** [comment]
@agektmr Sorry, I am not sure what other actions I need to take to get this to go through.

**Comment by sotayamashita** [comment]
@agektmr I have already signed. How about @chikathreesix ?

**Comment by agektmr** [comment]
@sotayamashita @chikathreesix Do you know how we get the bot to recognize @kennith 's and machine-translation 's (if such thing exists) signatures?
screen shot 2017-11-24 at 15 41 00

**Comment by sotayamashita** [comment]
@agektmr What about to squash commit to overwrite commit history of the PR? Next time, we will replace machine translation commit with person who sent a PR.

**Comment by agektmr** [comment]
@sotayamashita Not sure how that works. I don't want to take @kennith 's credit out.
The source repo is [here](https://github.com/agektmr/WebFundamentals/tree/gitlocalize-326). Perhaps @kennith can fork it and squash then send a separate PR? Does that work?

**Comment by agektmr** [comment]
This PR looks good to me once CLA issue is resolved.

**Comment by agektmr** [comment]
@kennith can you squash this PR?

**Comment by sotayamashita** [comment]
We have signed Corporate CLA but it will takes time to accept a few days according FAQ for Google CLA. https://cla.developers.google.com/about

**Comment by petele** [comment]
Due to the way DevSite works, localizing some files will cause some pretty serious headaches:
* `_book.yaml`, `_toc.yaml` or `_upper_tabs-*.yaml`
* `_project.yaml`

But, we can do `_footer.yaml`!

Sorry! :(

**Pull request closed without merging**
