### PR TITLE
Fix Korean typo

### PR DESCRIPTION
**Pull request by simsim0709**
What's changed, or what was fixed?

It fixes the Korean translation typo.

- [ ] This has been reviewed and approved by (NAME)
- [x] I have run `npm test` locally and all tests pass.
- [ ] I have added the appropriate `type-something` label.
- [ ] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele

### CODE REVIEW

**Comment by petele** [comment]
Thanks for doing this, could I ask one more favor of you? It looks like 'service worker' was translated to 'service walker' in several cases. Could you do a sweep and correct those?

**Comment by simsim0709** [comment]
@petele I searched for "service walker", "walker", "walk". I wasn't able to find any. Could you spot one? 
Thanks 😄

**Comment by cwdoh** [comment]
@petele Have translated the Ko translation into en and then found it? it is some wrong translation from g.translator. :)

**Comment by cwdoh** [comment]
LGTM. :)

**Comment by cwdoh** [comment]
ping @simsim0709, could you check some conflict files of this PR?

**Comment by simsim0709** [comment]
@cwdoh. I just fixed merge conflict. Thanks.

**Pull request merged**
