### PR TITLE
Icon should be 192px not 196px

### PR DESCRIPTION
**Pull request by ebidel**
R: @jeffposnick

### CODE REVIEW

**Comment by jeffposnick** [comment]
:100: :nine: :two: :+1:

**Comment by PaulKinlan** [comment]
Wait. Don't pull this yet.

**Comment by ebidel** [comment]
:hourglass_flowing_sand: ing

**Comment by PaulKinlan** [comment]
Sorry, yes. 192 is correct based on 1.5 x 128 dp... Just double checked
base don't other doc as well.

Lgtm

**Comment by ebidel** [comment]
Builds appear to be stalled....

**Comment by ebidel** [comment]
Travis is back in action. Can you merge?

**Pull request merged**
