### PR TITLE
Remove migrated content

### PR DESCRIPTION
**Pull request by mathiasbynens**
These posts on JavaScript language features are now being maintained on https://v8.dev/features.

- <https://developers.google.com/web/fundamentals/primers/modules> redirects to <https://v8.dev/features/modules>.
- <https://developers.google.com/web/updates/2017/06/object-rest-spread> redirects to <https://v8.dev/features/object-rest-spread>.
- <https://developers.google.com/web/updates/2017/10/intl-pluralrules> redirects to <https://v8.dev/features/intl-pluralrules>.
- <https://developers.google.com/web/updates/2017/10/promise-finally> redirects to <https://v8.dev/features/promise-finally>.
- <https://developers.google.com/web/updates/2017/11/dynamic-import> redirects to <https://v8.dev/features/dynamic-import>.
- <https://developers.google.com/web/updates/2018/05/bigint> redirects to <https://v8.dev/features/bigint>.
- <https://developers.google.com/web/updates/2018/10/intl-relativetimeformat> redirects to <https://v8.dev/features/intl-relativetimeformat>.
- <https://developers.google.com/web/updates/2018/12/class-fields> redirects to <https://v8.dev/features/class-fields>.
- <https://developers.google.com/web/updates/2018/12/intl-listformat> redirects to <https://v8.dev/features/intl-listformat>.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Adding DO NOT MERGE until the redirects are live.

**Comment by mathiasbynens** [comment]
Do I get bonus points for this?

image

**Comment by mizansurovi** [comment]
Digital Marketing! | Work From Home! 
Make money online without any expenses!
Our Journey Since 24.12.2012
Subscribe & help us to build a blog !
http://www.mizansurovi1.blogspot.com
1 banner

**Comment by petele** [comment]
How are you doing the redirects?

**Comment by mathiasbynens** [comment]
@petele See DevSite CL 252053791. (Has been merged, but not yet deployed.)

**Comment by petele** [comment]
> See DevSite CL 252053791. (Has been merged, but not yet deployed.)

OK, you could have also put that into https://github.com/google/WebFundamentals/blob/master/src/content/en/_redirects.yaml

**Comment by petele** [comment]
Spoke with @mathiasbynens via IM, this is good to go.

**Comment by mathiasbynens** [comment]
Per @petele, DevSite does not enable the redirects as long as the content exists, so we should just merge this.

**Comment by petele** [comment]
PS: the redirects have been placed within the DevSite redirects, which is why they're not listed in here.

**Pull request merged**
