### PR TITLE
fix: missing comma in sample code

### PR DESCRIPTION
**Pull request by real34**
What's changed, or what was fixed?
- code sample

**Fixes:** #issue

**Target Live Date:** YYYY-MM-DD

- [ ] This has been reviewed and approved by (NAME)
- [ ] I have run `npm test` locally and all tests pass.
- [ ] I have added the appropriate `type-something` label.
- [ ] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele

### CODE REVIEW

**Comment by real34** [comment]
@googlebot I signed it!

**Comment by petele** [comment]
@real34 - can you sign the CLA please?

**Comment by real34** [comment]
@petele Hi! I signed it on the 1tth of November.
Just updated it weth my Github username: https://cla.developers.google.com/clas/edit?id=111881763572827450519&kind=KIND_INDIVIDUAL&domain=DOMAIN_GOOGLE

Did I make something wrong?

**Comment by petele** [comment]
@real34 - thanks, not sure why it didn't show as signed...

**Pull request merged**
