### PR TITLE
[zh-cn] Performance > Loading Performance > Optimizing JavaScript > Reduce JavaScript Payloads with Code Splitting

### PR DESCRIPTION
**Pull request by kennith**
https://developers.google.com/web/fundamentals/performance/optimizing-javascript/code-splitting/

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/zh-CN/review/8501)

### CODE REVIEW

**Comment by kennith** [comment]
@mt-gitlocalize and @jinziyi Can you sign the [CLA](https://cla.developers.google.com/)?

**Comment by jinziyi** [comment]
I have signed the CLA just now @kennith

**Comment by agektmr** [comment]
@limhenry @kennith can you review this PR? I can merge if it gets LGTM.

**Comment by kennith** [comment]
@agektmr I already reviewed and it is good to merge.

**Comment by agektmr** [comment]
Merged. Thank you for your contribution!

**Pull request merged**
