### PR TITLE
Translate page on Russian

### PR DESCRIPTION
**Pull request by DmitrySkripunov**
Translate page on Russian

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/ru/review/409)

### CODE REVIEW

**Comment by DmitrySkripunov** [comment]
@petele sorry, I didn't urderstand what is wrong. Can I get more explanation?

**Comment by petele** [comment]
If you look at [_common-links.md](https://github.com/google/WebFundamentals/blob/master/src/content/en/_common-links.md), there's an additional line at the bottom that's not included in this translation.

**Comment by DmitrySkripunov** [comment]
@petele ok, I see, thnaks. This is some problem GitLocalize. I contacted their support.

**Comment by petele** [comment]
@sotayamashita & @chikathreesix - would you please take a look! looks like some content was lost here.

**Comment by sotayamashita** [comment]
@DmitrySkripunov I have created a PR to fix the issue @petele say. Please check this out.
https://github.com/DmitrySkripunov/WebFundamentals/pull/1

**Comment by DmitrySkripunov** [comment]
@petele look, please. I made translate for new text block from PR @sotayamashita

**Pull request merged**
