### PR TITLE
typo: supoort -> support

### PR DESCRIPTION
**Pull request by tophf**

### CODE REVIEW

**Comment by tophf** [comment]
er, forget it, too much trouble for the simple typo

**Comment by petele** [comment]
Hey @tophf - thanks for the PR! I understand the PR process can be a pain, instead, if you want to file an issue, we'll make sure to get it fixed ASAP.

**Comment by tophf** [comment]
Nah, I might have come round to liking this typo, it's fun, and probably reflects the actual state of affairs.

**Comment by petele** [comment]
Awesome, or just think of someone saying it in an accent.

**Pull request closed without merging**
