### PR TITLE
Rendering on the web

### PR DESCRIPTION
**Pull request by developit**
What's changed, or what was fixed?
- Added update discussing various rendering strategies.

**Target Live Date:** asap

- [x] This has been reviewed and approved by (@addyosmani)
- [x] I have run `npm test` locally and all tests pass.
- [x] I have added the appropriate `type-something` label.
- [ ] I've staged the site and manually verified that my content displays correctly.

**CC:** @petele

### CODE REVIEW

**Comment by developit** [comment]
note: warnings are in link URLs.

**Comment by addyosmani** [comment]
Approved but I believe @developit wanted to add a few more diagrams before we land this.

**Comment by developit** [comment]
@addyosmani images added!

**Comment by addyosmani** [comment]
🚀

**Pull request merged**
