### PR TITLE
Add Feature Policy for Autoplay

### PR DESCRIPTION
**Pull request by beaufortfrancois**
What do you think @mounirlamouri?

### CODE REVIEW

**Comment by mounirlamouri** [comment]
lgtm

/cc @rebeccahughes

**Comment by beaufortfrancois** [comment]
I've reopened it at https://github.com/google/WebFundamentals/pull/5364

**Comment by rebeccahughes** [comment]
Looks good, do we want to mention its behind chrome://flags for now?

**Comment by beaufortfrancois** [comment]
That is a great idea. I'll update the PR to incorporate these changes as well.

**Pull request merged**
