### PR TITLE
[Translation it] Performance > Optimizing content efficiency > Automating-image-optimization

### PR DESCRIPTION
**Pull request by lucab85**
Italian translation of Performance > Optimizing Content Efficiency > Automating-image-optimization.

Please review by @carlaofarrell

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/it/review/457)

### CODE REVIEW

**Comment by petele** [comment]
@sotayamashita & @chikathreesix - would you please take a look at why it's getting `CLA: No`

**Comment by sotayamashita** [comment]
`CLA: No` for any of the following reasons: :thinking:

- @lucab85 have squashed commits and one of the commit is created by `mt-gitlocalize`?
- @lucab85 have not signed CLA yet?

@petele @agektmr Any idea?

**Comment by lucab85** [comment]
I've already signed CLA early this year.
Gitlocalize created this branch with two commits (one from my e-mail address on-behalf of mt@gitlocalize.com and one from mt@gitlocalize.com). So I squashed into one commit to fix the from address and also sign with my GPG.

**Comment by agektmr** [comment]
The googlebot message above says:

    This is a terminal state, meaning the cla/google commit status will not change from this State.
    It's up to you to confirm consent of the commit author(s) and merge this pull request when appropriate.

As @lucab85 is the only committer in this pull request, I think it's safe to merge this.

cc: @petele

**Comment by lucab85** [comment]
Could be possible for the googlebot evaluate CLA at any commit?

**Comment by sotayamashita** [comment]
@lucab85 I would appreciate if you could not squash your commit to investigate in next time. Thanks in advance.

**Comment by petele** [comment]
@carlaofarrell - would you mind taking a look please?

**Comment by carlaofarrell** [comment]
Hi Pete,

I will look at it shortly. Thank you! 

Carla

**Comment by carlaofarrell** [comment]
I cannot locate Performance > Rendering > Automating-image-optimization (#5519) in the EN folder nor in the IT.

**Comment by lucab85** [comment]
@carlaofarrell The EN source is locate under: `src/content/en/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/index.md`

**Comment by carlaofarrell** [comment]
@lucaberton Thank you, I got the source text. Can you please also send me the link for the editable Italian translation?

I cannot find it in  <https://github.com/google/WebFundamentals> WebFundamentals/ <https://github.com/google/WebFundamentals/tree/master/src> src/ <https://github.com/google/WebFundamentals/tree/master/src/content> content/ <https://github.com/google/WebFundamentals/tree/master/src/content/it> it/ <https://github.com/google/WebFundamentals/tree/master/src/content/it/fundamentals> fundamentals/ <https://github.com/google/WebFundamentals/tree/master/src/content/it/fundamentals/performance> performance/ <https://github.com/google/WebFundamentals/tree/master/src/content/it/fundamentals/performance/optimizing-content-efficiency> optimizing-content-efficiency

**Comment by lucab85** [comment]
@carlaofarrell You can find the file in this PR: 
[text file of "automating-image-optimization/index.md"](https://github.com/lucab85/WebFundamentals/blob/1ad0a76c6e415c8928b836ae18c8611cc70c58c8/src/content/it/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/index.md) inside of [commit 1ad0a76](https://github.com/google/WebFundamentals/pull/5519/commits/1ad0a76c6e415c8928b836ae18c8611cc70c58c8)

**Comment by carlaofarrell** [comment]
Just a note: this post is very long so it will take me few days to review it.

**Comment by petele** [comment]
@carlaofarrell - any updates on the progress of this one?

**Comment by carlaofarrell** [comment]
Hi Pete,

I’m currently traveling. I will be back in California on 01/31. 

In any case I have been working on this article on and off for few days now. It is about 20k words, which in the ‘editing/revision’ world translates into about 20 hrs of work. And these translations need a fair bit of editing, as I mentioned to Peter. 
Sorry in any case that is taking me so long. 

Please expect delays in the editing of the other articles as well until I’m OOO. 
> @carlaofarrell - any updates on the progress of this one?
>

**Comment by lucab85** [comment]
Hi @carlaofarrell ,
would you mind to review this PR, please.

**Pull request merged**
