### PR TITLE
Update DevTools Network Conditions docs.

### LINKED ISSUE #2471: Update Network Conditions
Taking a peek at [network conditions](https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/network-conditions?hl=en) there is quite a bit of room to improve here. I propose:

1. Drop the external tooling. DevTools now throttles uploads as well as downloads. The only stuff not throttled is WebRTC, Service Workers, and other non-primary (probably not the right term) work. Which a note can be made about the options to throttle even those with external tools.
2. Update the page to focus on the Network Throttle that is now built into the Network Panel.
    1. Update to show the new UX.
    2. Show how to create custom conditions via settings

Anything else to do when updating? Or any reason to keep the full instructions on using other tools?

cc @paulirish @kaycebasques @Meggin @pbakaus

### PR DESCRIPTION
**Pull request by Garbee**
Overhauled the network conditioning documentation page to show the latest user experience.

With this, added myself to the contributors file since it is a substantial enough modification I think.

Fixes #2471

### CODE REVIEW

**Comment by Garbee** [comment]
Looks like I am missing a required key in the `_contributors.yml` entry. Does anyone spot what it is?

**Comment by crhym3** [comment]
`email`?

**Comment by Garbee** [comment]
Not email and not a missing space in one of the list indexes.

**Comment by Garbee** [comment]
Ah, looks like most of my second-level indexes were a space off.

/me sighs.

Sorry for the stupidity. Thanks for maintaining the nice build system @crhym3!

**Comment by Garbee** [comment]
Now that the build is passing, @kaycebasques or @pbakaus want to review the content please?

**Comment by kaycebasques** [comment]
on it

**Comment by kaycebasques** [comment]
LGTM, thanks @Garbee! Closes #2471.

**Pull request merged**
