### PR TITLE
[Translation zh-tw] Fundamentals  > Billions

### PR DESCRIPTION
**Pull request by kennith**
@limhenry Can you review this translation? 

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/zh-TW/review/432)

### CODE REVIEW

**Comment by henrylim** [comment]
@kennith, you're looking for @limhenry.

**Comment by petele** [comment]
@agektmr, @kennith, @limhenry - it looks like GitLocalize is adding extra quotes to this

**Comment by agektmr** [comment]
@sotayamashita @chikathreesix can you take a look?

**Comment by sotayamashita** [comment]
@agektmr I'll check it out.

**Comment by petele** [comment]
@sotayamashita & @chikathreesix - also has commits by @mt-gitlocalize - which has not signed the CLA

**Comment by petele** [comment]
any updates on this?

**Comment by agektmr** [comment]
Check the email I sent you late last year. I've bumped it. @petele

**Comment by petele** [comment]
CLA is fine, but there are still issues with extra quotes in the markdown.

**Comment by limhenry** [comment]
i can recreate this PR (w/o using GitLocalize). Maybe this is the easiest/fastest way to fix it?

**Comment by limhenry** [comment]
Created a new PR here: #5608. You may close this PR.

**Pull request closed without merging**
