### PR TITLE
[Translate ru] Accessibility -> focus

### PR DESCRIPTION
**Pull request by DmitrySkripunov**
[Check out a review request at GitLocalize](https://gitlocalize.com/repo/107/ru/review/1684)

### CODE REVIEW

**Comment by Ann40a** [comment]
Does anybody know what can I do with this error? Or isn't it my fault and I can do nothing?

image

**Comment by DmitrySkripunov** [comment]
@Ann40a I guess it is trouble with GitLocalize user. @agektmr, I'm right?

**Comment by agektmr** [comment]
@Ann40a Have you already signed CLA? https://cla.developers.google.com/

**Comment by Ann40a** [comment]
Yes, it is signed from December and I had no problem with it before.
image

image

And as you can see from error message "SLAs are signed", but I have no idea what does "unable to verify author consent" mean and what can I do from my side.

**Comment by agektmr** [comment]
As long as CLA is signed I don't think there are issues to merge. cc: @petele

**Comment by ilyaspiridonov** [comment]
@agektmr Reviewed

**Comment by isalconost** [comment]
@Ann40a Based on this https://travis-ci.org/google/WebFundamentals/builds/381548099?utm_source=github_status&utm_medium=notification
it looks like Travis can't find you in the Contributors list: https://github.com/google/WebFundamentals/blob/master/src/data/_contributors.yaml
Can you please add yourself?

@agektmr If the a.m. issue (missing contributor) doesn't break anything, this one can be merged as well.

**Comment by Ann40a** [comment]
@googlebot I consent

**Comment by ilyaspiridonov** [comment]
@Ann40a
ERROR: src/data/_contributors.yaml Identifier must contain only letters, was 'ann40a'

Sorry about that )
It probably expects something like 'annasorokina' as the ID

**Comment by ilyaspiridonov** [comment]
Phew! Thanks everyone
@agektmr this one is good to go

**Pull request merged**
