### PR TITLE
Update index.markdown

### PR DESCRIPTION
**Pull request by yuzver**
Details: https://github.com/google/WebFundamentals/issues/1070

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Please sign CLA at https://developers.google.com/open-source/cla/individual

**Comment by denpatin** [comment]
@PaulKinlan Btw, how soon will the modifications be applied to the website?

**Comment by PaulKinlan** [comment]
We need to do a build to the internal infrastructure so hopefully this
week.  We need to improve the cadence of the public releases

**Comment by denpatin** [comment]
@PaulKinlan Ah ok! Just thought about whether changes get applied individually and instantly or in batch and after some time. GL!

**Pull request merged**
