### PR TITLE
Switch from travis-ci to drone.io

### PR DESCRIPTION
**Pull request by crhym3**
Let's see if this works.

New build history page:
https://drone.io/github.com/google/WebFundamentals

### CODE REVIEW

**Comment by crhym3** [comment]
hm... drone doesn't show build status here for some reason.

**Comment by crhym3** [comment]
let me try something else. please don't merge yet.

**Comment by arthurvr** [comment]
> 	Switch from travis-ci to drone.io

Haven't followed up on this project that much, but I'm interested why.

**Comment by crhym3** [comment]
It's slow on starting builds.

**Comment by crhym3** [comment]
It's working fine now but the build is taking 10 min on average :(

**Pull request merged**
